apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: "[{\n  \"apiVersion\": \"memsql.com/v1alpha1\",\n  \"kind\": \"\
      MemsqlCluster\",\n  \"metadata\": {\n    \"name\": \"memsql-cluster\"\n  },\n\
      \  \"spec\": {\n    \"license\": \"BDVhNDg5OWFjNTc3OTQxODRhOTVlMWVlZWY1YTFlNTlkAAAAAAAAAAAEAAAAAAAAAAwwNgIZAPXaOk16AZMCIzdmkvvO0VH57SIhkshiMAIZAJYHyL5vkNE4Sohz8BDqMuikVj9lNLvy4w==\"\
      ,\n    \"adminHashedPassword\": \"*FABE5482D5AADF36D028AC443D117BE1180B9725\"\
      ,\n    \"releaseID\": \"722ce44d-6f95-4855-b093-9802a9ae7cc9\",\n    \"redundancyLevel\"\
      : 1,\n    \"aggregatorSpec\": {\n      \"count\": 3,\n      \"height\": 0.5,\n\
      \      \"storageGB\": 256,\n      \"storageClass\": \"standard\"\n    },\n \
      \   \"leafSpec\": {\n      \"count\": 1,\n      \"height\": 1,\n      \"storageGB\"\
      : 1024,\n      \"storageClass\": \"standard\"\n    }\n  }\n}]"
    capabilities: Seamless Upgrades
    categories: Database, OpenShift Optional
    certified: 'true'
    containerImage: registry.connect.redhat.com/memsql/operator:ubi-v0.0.2
    createdAt: '2019-03-27T12:59:59'
    description: Install a MemSQL Cluster
    support: MemSQL
  name: memsql-operator.v0.0.2
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - description: MemSQL
        displayName: MemSQL
        kind: MemsqlCluster
        name: memsqlclusters.memsql.com
        resources:
          - kind: MemsqlCluster
            name: ''
            version: v1alpha1
        specDescriptors:
          - description: License key from portal.memsql.com
            displayName: License Key
            path: license
          - description: Admin Hashed Password, see docs to generate.
            displayName: Admin Hashed Password
            path: adminHashedPassword
          - description: Number of availability groups; 1 or 2
            displayName: Redundancy Level
            path: redundancyLevel
          - description: Number of aggregator nodes.  3 is recommended.
            displayName: Aggregator Node Count
            path: aggregatorSpec.count
          - description: height=1 corresponds to one MemSQL License Unit (8vCPU/32GB
              RAM)
            displayName: Aggregator Node Height
            path: aggregatorSpec.height
          - description: size of the persistent volume claim in GB
            displayName: Aggregator Storage
            path: aggregatorSpec.storageGB
          - description: name of the Kubernetes storage class for the persistent volume
              claim
            displayName: Aggregator PVC Storage Class
            path: storageClass
          - description: Number of Leaf nodes. Count will automatically be doubled
              if redundancyLevel=2
            displayName: Leaf Node Count
            path: leafSpec.count
          - description: height=1 corresponds to one MemSQL License Unit (8vCPU/32GB
              RAM)
            displayName: Leaf Node Height
            path: leafSpec.height
          - description: size of the persistent volume claim in GB
            displayName: Leaf Storage
            path: leafSpec.storageGB
          - description: name of the Kubernetes storage class for the persistent volume
              claim
            displayName: Leaf PVC Storage Class
            path: leafSpec.storageClass
        statusDescriptors:
          - description: Master Aggregator
            displayName: DDL Endpoint
            path: ddlEndpoint
          - description: Child Aggregator(s)
            displayName: DML Endpoint
            path: dmlEndpoint
          - description: Number of expected nodes based on current configuration.
            displayName: Expected Nodes
            path: expectedNodes
          - description: Number of nodes which are ready (running MemSQL, accepting
              connections, participating in the cluster)
            displayName: Ready Nodes
            path: readyNodes
        version: v1alpha1
  description: "This package contains everything you need to run the MemSQL Kubernetes\
    \ Operator\nin your own Kubernetes cluster.\n\n# Getting Started\n\n* Install\
    \ RBAC resources\n    ```bash\n    kubectl create -f rbac.yaml\n    ```\n* Install\
    \ the MemSQL Cluster CRD\n    ```bash\n    kubectl create -f memsql-cluster-crd.yaml\n\
    \    ```\n* Deploy the Operator\n    ```bash\n    kubectl create -f deployment.yaml\n\
    \    kubectl get deployments\n    kubectl get pods\n    ```\n\n# Creating a cluster\n\
    \n* Edit the memsql-cluster.yaml file for your MemSQL cluster\n    * name -> cluster\
    \ name of your choice\n    * license -> license key from portal.memsql.com\n \
    \   * releaseID -> use \"722ce44d-6f95-4855-b093-9802a9ae7cc9\" (MemSQL v6.7.14)\n\
    \    * adminHashedPassword -> `HASHED_PASSWORD`\n        * see below Python script\
    \ to convert your password, include the leading `*`\n\n    * Python function to\
    \ hash your password:\n        ```python\n        from hashlib import sha1\n \
    \       print(\"*\" + sha1(sha1('mypassword').digest()).hexdigest().upper())\n\
    \        ```\n\n    * redundancyLevel -> 1 or 2\n    * units -> number of nodes.\
    \ Leaf nodes will automatically be doubled if redundancyLevel=2\n    * height\
    \ -> height=1 corresponds to one MemSQL License Unit (8vCPU/32GB RAM)\n    * storageGB\
    \ -> size of the persistent volume claim in GB\n    * storageClass -> name of\
    \ the Kubernetes storage class for the\n      persistent volume claim\n    * NOTE:\
    \ the minimum production config should be:\n        * 1 leaf unit @ height 1\n\
    \        * 3 aggregator units @ height 0.5\n        * redundancyLevel = 2\n\n\
    * Create the cluster.\n    ```bash\n    kubectl create -f memsql-cluster.yaml\n\
    \    ```\n\n* To get logs for operator (or any MemSQL node), run the following\
    \ after looking\n  up the PODNAME using `kubectl get pods`:\n    ```bash\n   \
    \ kubectl logs PODNAME\n    ```\n\n* To get info about all MemSQL clusters running,\
    \ use these commands. -oyaml will expose the DDL/DML endpoints for MemSQL.\n \
    \   ```bash\n    kubectl get memsql\n    kubectl describe memsql\n    ```\n\n\
    * To see all the pods, services, stateful sets, & resources used by the MemSQL\
    \ cluster, run:\n    ```bash\n    kubectl get all\n    ```\n\n* Connect to the\
    \ MemSQL cluster.\n  Use the DDL endpoint for creating tables.\n  DML endpoint\
    \ (load balancer amongst other aggregators) can be used for read/write\n  workload.\
    \ Use the user called \"admin\" with the password you defined during\n  cluster\
    \ creation.\n    ```bash\n    mysql -u admin -h <hostname> -P <port> -p<password>\n\
    \    ```\n\n* Notes on editing a MemSQL cluster:\n    * The MemSQL operator supports\
    \ scaling and changing certain parts of the spec. Currently you can change:\n\
    \        * units\n        * height\n        * releaseID\n        * adminHashedPassword\n\
    \        * license\n        * redundancyLevel\n\n* To delete the MemSQL cluster:\n\
    \    ```bash\n    kubectl delete -f memsql-cluster.yaml\n    ```\n"
  displayName: MemSQL
  icon:
    - base64data: iVBORw0KGgoAAAANSUhEUgAAAHgAAAB4CAYAAAA5ZDbSAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAibSURBVHgB7Z1bbBRVGMc/5FYptBKFAtJQjVxiGyHcQ0iKQrCAkUAgfeJiIjVAAi+tPiEQEhMBHyCCUF5AHrQQqxgQJSiQGAwSCJAWRa61UFsqFirFVjB6/meZZXeY2e7Ozm0/v1/SbO2ezuj8zvc/l5mtXfLmr/2XBLY8QQJrRDBzRDBzRDBzRDBzRDBzRDBzRDBzRDBzRDBzRDBzRDBzRDBzRDBzRDBzRDBzRDBzRDBzRDBzRDBzRDBzRDBzRDBzRDBzRDBzRDBzRDBzRDBzRDBzRDBzRDBzMlJwXt/etLHsNRo7fDBtWvY6eYlxnsPryyi/fy5lGhkpeMG0MfTS8wP196VTRlH5/GLyggXTRkfPU1QwgDYtnU2ZRsYJnj5mmP6KBYInFQ4hN0FKoCPFMqmwgErGDadMIqMERy76aMv3Ni2bTTm9epJbIJr9OI/XZJRgVFRe3z6W7+X3e4oqXIpqdCK78+RmZ9Hm5ZkT1Rkj2CqazSyZNTHtqLaKZjMl40ZkTFRnhOBE0Wwm3Qi1i2a3z+MXGSE4UTSbSSeqE0WzmUyJ6tALTiaazTiJ6pFqOdRZNJvJhKgOteBUotlMKhGandXD8Vo67FEdasGpRLOZVKJ6YRrnCXtUh1awk2g2k0xUI5rnTC6idAhzVIdScDrRbCZRhKYTzamcJ0hCKTidaDaTKKoXungeRPW6xa9S2AidYDei2YxVVLsRzWZw48PtPfF0CZVgN6PZDCLUuN2H83h1BypsUR0qwW5GsxlE9ckPV9LYYYNp28q5np6nwqPO44TQCPYimu3IzvK2wtzYE3eLUAj2MpqDIixRHQrBXkZzUIQlqgMX7Gc0+00YojpQwRyj2UzQUR2o4HSi+W7739Tweyt9ffICeQXOcejUL/o89c23yQlBR3VggtOJ5t2HT9HcNbuo4VYrLd5QReOWb3YswI5zVxpo6aZq2rj3mD4PzoHvnRBkVAciGHvATqL5UsMftHRztRJ8Ou7nkJuOgFhQtR/t/4HKKw9QU8ufce/h+E47U1BRHYhgJ3vAqNplmz+jyw23bNukIwCgA1VU7qfPv6+xbeO0MwUV1b4LTnUPuLHlrmXV2uFUQLWS2lkHisVJZwoiqn0VnOrtOVx0jIPJXvRYkhWADlSuqnabiuVUcdKZ/I5qXwUnG82xF72tvYOcAgFT366kyq9OWL5vdKBzV36jdEilmv2O6q69C19eQz6AaF4xZ3Kn7XDR3/vkO7ru0qy44/4DOnLmMh0/f42KCgbS4dMXqV9uNm1QUg6c+InuP/iH3KD1XjvteNiR8BGXRIxRNzzw71PffIe8posf//dRRHNnd3BQtRv3Hk27msIAqrR6zUL9aodOl4rtqmM4T6hk8KWC3ywZT2OH59u+73bVBo1RzTnZWTRm6GDLNngCJKt7Nzpy9jJ5ieeCE0UzqnbN7kOuRmWYMIYGRDaEmvEjqj2fZNnNmt2a4ISd47V1CSd66xZ5+xxXN/KY7CfjlwScxtpkaW1rp3d3fqP2zX+OPDoUMzYXFgwgL/E8ont066piepD+nttYmyqI4qpjZ6lnj27RsRlLrOPn68grfJlFG7Nn897u/xldxV2U9JvednbPIxqI2Mep9ynF5M8oMceXCrYDE4zWe3+pmLqTsE39zRa9IZCT3VP/tRszd9QkpvZak6NjGmApUzQkT69dsXTB7NcMzj9j3IjoJMmuHZ6/Rpuaq42eb2R0RqCCsUSob26hlVu/tHwfF+rb9WV6nxcXCnLLZk6kg2o2GktOr0eCccyaukY9a7UCd3OqVy+KHhNgKRe/nCtW4q7R3LUfR3+CD5fhU4Q5vbLi2iFq567dFdehyudNodIpI+POERSBCgaTXizQd1esLkT5vOLHJiE11xqp6ujZTo45xPaYpcUj48Y/CIdcPPqzYss+vSGxZNaEaIeJtCmgnRWleodq5dZ9dPDHC7pdyfjh+sbB4fffomnvbE+YGkER+BiMLb0ydZ/UDKoXF9bJEmKP6gB2x0R0xoow4hapAIGQj+qvOnom2mbd4un6dWpFpe5cRrsdB07QKtVWd4qZEymMBC74oKocxJn5Himq1+kjOJ+qtabdMXeYdpQQ5/o9VYn4HfOfK8SYXDhkgI5sq5mvIRzJEEZCMYuuMlWcUWlWUYwLiTE09gtiYsHOEX4Xn/aLPSYS4aDpKczaq020aldkvMYuEz6/hL9/aYguKsjTr4n2iyHeaq85DAQ+BgPs02IyZVQsxmXs+FiBnydT2Thm9eqF0YotLR5l+3uI2qojZ2mGGlMxS0bHQAfDJCuM42oqhKKCH1VcpBJRpZ1NpJI5JiZOxjNQmHglOiZiFu/jMVwsfVDterxW1Yn3MIu2etQGlW5EeBgJzUYHKm6GuoiQ7NbeLIRh3MUx7RIBgmIjGeRmR0QaY26lqnDjE/yx7fA9hghgt9QLmlBENEDF/arGOVxEzFbtwGZDfv/Hn5Sw2tONCOqiZrgT6I0NeyyPV/IwklGxtWoJNlhVLTZCYm/vIdqxBke7GeNH6A0MUPTcAL0uRtVbTcBOblkR989YYqHTFapxHR2mRi3F8OrlfrRvz2RZgf+4UxevU8f9yM3+Szdu0c3bd+OecohciMZIG7U5/8rIoXqMNn8ZH2GJHPNG9Pdr65r0Tpf5mMZ5T6u2kJPfry+9MOgZar7dpuV+YBqvvzheq9v1z+2joxtye3aP1Adu3OfqHbC66PFb2zr0Wjr2y7i5n9Wju16jD332af2Kzu0VvtxN4grG9yI1/iIFsD262CYlgkQEM0fuJjFHBDNHBDNHBDNHBDNHBDNHBDNHBDNHBDNHBDNHBDNHBDNHBDNHBDNHBDNHBDNHBDNHBDNHBDNHBDNHBDNHBDNHBDNHBDNHBDNHBDNHBDNHBDNHBDNHBDNHBDNHBDNHBDNHBDNHBDNHBDPnP8D8tqZ0DeIuAAAAAElFTkSuQmCC
      mediatype: image/png
  install:
    spec:
      deployments:
        - name: memsql-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                name: memsql-operator
            template:
              metadata:
                labels:
                  name: memsql-operator
              spec:
                containers:
                  - env:
                      - name: WATCH_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.namespace
                      - name: POD_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                      - name: OPERATOR_NAME
                        value: memsql-operator
                    image: registry.connect.redhat.com/memsql/operator:ubi-v0.0.2
                    imagePullPolicy: Always
                    name: memsql-operator
                serviceAccountName: memsql-operator
      permissions:
        - rules:
            - apiGroups:
                - ''
              resources:
                - pods
                - services
                - endpoints
                - persistentvolumeclaims
                - events
                - configmaps
                - secrets
              verbs:
                - '*'
            - apiGroups:
                - policy
              resources:
                - poddisruptionbudgets
              verbs:
                - '*'
            - apiGroups:
                - ''
              resources:
                - namespaces
              verbs:
                - get
            - apiGroups:
                - apps
                - extensions
              resources:
                - deployments
                - daemonsets
                - replicasets
                - statefulsets
              verbs:
                - '*'
            - apiGroups:
                - memsql.com
              resources:
                - '*'
              verbs:
                - '*'
          serviceAccountName: memsql-operator
    strategy: deployment
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: false
      type: AllNamespaces
  keywords:
    - database
    - sql
    - distributed
    - relational
    - memory
  links:
    - name: MemSQL
      url: https://www.memsql.com
    - name: Blog
      url: https://www.memsql.com/blog
    - name: Documentation
      url: https://docs.memsql.com
    - name: Forum
      url: https://www.memsql.com/forum
  maintainers:
    - email: info@memsql.com
      name: MemSQL
  maturity: alpha
  provider:
    name: MemSQL
  version: 0.0.2
