apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: memsqlclusters.memsql.com
spec:
  additionalPrinterColumns:
    - JSONPath: .spec.aggregatorSpec.count
      description: Number of MemSQL Aggregators
      name: Aggregators
      type: integer
    - JSONPath: .spec.leafSpec.count
      description: Number of MemSQL Leaves (per availability group)
      name: Leaves
      type: integer
    - JSONPath: .spec.redundancyLevel
      description: Redundancy level of MemSQL Cluster
      name: Redundancy Level
      type: integer
    - JSONPath: .metadata.creationTimestamp
      name: Age
      type: date
  group: memsql.com
  names:
    kind: MemsqlCluster
    listKind: MemsqlClusterList
    plural: memsqlclusters
    shortNames:
      - memsql
    singular: memsqlcluster
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
