version: '3.6'
services:

  kafka-rest-proxy:
    image: confluentinc/cp-kafka-rest:4.1.1-2
    hostname: kafka-rest-proxy
    # ports:
    #   - "8082:8082"
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: 11.11.157.135:2181
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082/
      KAFKA_REST_HOST_NAME: kafka-rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: 11.11.157.135:9092
    networks:
      - esnet

  kafka-topics-ui:
    image: landoop/kafka-topics-ui:0.9.3
    hostname: kafka-topics-ui
    ports:
      - "0.0.0.0:8000:8000"
    environment:
      KAFKA_REST_PROXY_URL: "http://kafka-rest-proxy:8082/"
      PROXY: "true"
    depends_on:
      - kafka-rest-proxy
    networks:
      - esnet

networks:
  esnet: