apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: "[\n  {\n    \"apiVersion\": \"ubixlabs.com/v1alpha1\",\n    \"\
      kind\": \"Ubix\",\n    \"metadata\": {\n      \"name\": \"example-ubix\"\n \
      \   },\n    \"spec\": {\n      \"cassandra\": {\n        \"enable\": \"yes\"\
      ,\n        \"image\": \"ubix/cassandra\",\n        \"imageTag\": \"v2\"\n  \
      \    },\n      \"defaultImageTag\": \"v1\",\n      \"elasticsearch\": {\n  \
      \      \"enable\": \"yes\",\n        \"image\": \"ubix/elasticsearch\",\n  \
      \      \"imageTag\": \"v2\"\n      },\n      \"hdfs\": {\n        \"datanodeImage\"\
      : \"ubix/hadoop\",\n        \"datanodeImageTag\": \"v2\",\n        \"datanodeReplicas\"\
      : 1,\n        \"enable\": \"yes\",\n        \"namenodeImage\": \"ubix/hadoop\"\
      ,\n        \"namenodeImageTag\": \"v2\"\n      },\n      \"imageRegistry\":\
      \ \"registry.ubix.io\",\n      \"metastore\": {\n        \"enable\": \"yes\"\
      ,\n        \"image\": \"ubix/hive\",\n        \"imageTag\": \"v3\"\n      },\n\
      \      \"mongo\": {\n        \"enable\": \"yes\",\n        \"image\": \"ubix/mongo\"\
      ,\n        \"imageTag\": \"v1\"\n      },\n      \"portal\": {\n        \"enable\"\
      : \"yes\",\n        \"image\": \"ubix/portal\",\n        \"imageTag\": \"v3\"\
      \n      },\n      \"postgres\": {\n        \"enable\": \"yes\",\n        \"\
      image\": \"ubix/postgres\",\n        \"imageTag\": \"v7\"\n      },\n      \"\
      spark\": {\n        \"enable\": \"yes\",\n        \"masterImage\": \"ubix/spark\"\
      ,\n        \"masterImageTag\": \"v4\",\n        \"workerImage\": \"ubix/spark\"\
      ,\n        \"workerImageTag\": \"v4\",\n        \"workers\": 3\n      },\n \
      \     \"ubixDomain\": \"crc.ubix.io\",\n      \"ubixNamespace\": \"ubix\",\n\
      \      \"ui\": {\n        \"enable\": \"yes\",\n        \"nginxImage\": \"ubix/openresty\"\
      ,\n        \"nginxImageTag\": \"v4\",\n        \"uxFrameImage\": \"ubix/ux-frame\"\
      ,\n        \"uxFrameImageTag\": \"v4\"\n      },\n      \"workspaceManager\"\
      : {\n        \"enable\": \"yes\",\n        \"image\": \"ubix/workspace-manager\"\
      ,\n        \"imageTag\": \"v2\",\n        \"sparkCoresMax\": \"2\"\n      },\n\
      \      \"zookeeper\": {\n        \"enable\": \"yes\",\n        \"image\": \"\
      ubix/zookeeper\",\n        \"imageTag\": \"v3\"\n      }\n    }\n  }\n]"
    capabilities: Basic Install
    categories: AI/Machine Learning,Big Data
    description: Ubix platform
  name: ubix-operator.v0.0.1
  namespace: ubix
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - description: Custom resource for ubix deployment
        displayName: Ubix custom resource
        kind: Ubix
        name: ubixes.ubixlabs.com
        resources:
          - kind: Pod
            name: ''
            version: v1
          - kind: Service
            name: ''
            version: v1
        specDescriptors:
          - description: DNS domain to be used by the UBIX cluster
            displayName: Ubix Domain
            path: ubixDomain
            x-descriptors:
              - urn:alm:descriptor:com.tectonic.ui:text
          - description: Namespace
            displayName: Namespace
            path: ubixNamespace
            x-descriptors:
              - urn:alm:descriptor:com.tectonic.ui:namespaceSelector
          - description: Container registry to pull images from
            displayName: Image Registry
            path: imageRegistry
            x-descriptors:
              - urn:alm:descriptor:com.tectonic.ui:text
          - description: Default image tag to use
            displayName: Default image tag
            path: defaultImageTag
            x-descriptors:
              - urn:alm:descriptor:com.tectonic.ui:text
          - description: Specifies if Cassandra is enabled
            displayName: Enable Cassandra
            path: cassandra.enable
            x-descriptors:
              - urn:alm:descriptor:com.tectonic.ui:fieldGroup:Cassandra
              - urn:alm:descriptor:com.tectonic.ui:select:yes
              - urn:alm:descriptor:com.tectonic.ui:select:no
          - description: Cassandra container image repository
            displayName: Cassandra Image
            path: cassandra.image
            x-descriptors:
              - urn:alm:descriptor:com.tectonic.ui:fieldGroup:Cassandra
              - urn:alm:descriptor:com.tectonic.ui:text
          - description: Cassandra image tag
            displayName: Cassandra Tag
            path: cassandra.imageTag
            x-descriptors:
              - urn:alm:descriptor:com.tectonic.ui:fieldGroup:Cassandra
              - urn:alm:descriptor:com.tectonic.ui:text
          - description: Specifies if Elasticsearch is enabled
            displayName: Enable Elasticsearch
            path: elasticsearch.enable
            x-descriptors:
              - urn:alm:descriptor:com.tectonic.ui:fieldGroup:Elasticsearch
              - urn:alm:descriptor:com.tectonic.ui:select:yes
              - urn:alm:descriptor:com.tectonic.ui:select:no
              - urn:alm:descriptor:com.tectonic.ui:advanced
          - description: Elasticsearch container image repository
            displayName: Elasticsearch Image
            path: elasticsearch.image
            x-descriptors:
              - urn:alm:descriptor:com.tectonic.ui:fieldGroup:Elasticsearch
              - urn:alm:descriptor:com.tectonic.ui:text
              - urn:alm:descriptor:com.tectonic.ui:advanced
          - description: Elasticsearch image tag
            displayName: Elasticsearch Tag
            path: elasticsearch.imageTag
            x-descriptors:
              - urn:alm:descriptor:com.tectonic.ui:fieldGroup:Elasticsearch
              - urn:alm:descriptor:com.tectonic.ui:text
              - urn:alm:descriptor:com.tectonic.ui:advanced
          - description: Hive metastore
            displayName: Hive metastore
            path: metastore
          - description: Postgresql server
            displayName: Postgresql server
            path: postgres
          - description: UBIX Portal
            displayName: UBIX Portal
            path: portal
          - description: UBIX Workspace Manager
            displayName: UBIX Workspace Manager
            path: workspaceManager
          - description: Zookeeper
            displayName: Zookeeper
            path: zookeeper
          - description: HDFS
            displayName: HDFS
            path: hdfs
          - description: MongoDB server
            displayName: MongoDB server
            path: mongo
          - description: Spark
            displayName: Spark
            path: spark
          - description: UBIX UI
            displayName: UBIX UI
            path: ui
        statusDescriptors:
          - description: Status conditions
            displayName: Status conditions
            path: conditions
            x-descriptors:
              - urn:alm:descriptor:io.kubernetes.conditions
        version: v1alpha1
  description: Ubix platform
  displayName: Ubix Operator
  icon:
    - base64data: PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxzdmcKICAgeG1sbnM6c2tldGNoPSJodHRwOi8vd3d3LmJvaGVtaWFuY29kaW5nLmNvbS9za2V0Y2gvbnMiCiAgIHhtbG5zOmRjPSJodHRwOi8vcHVybC5vcmcvZGMvZWxlbWVudHMvMS4xLyIKICAgeG1sbnM6Y2M9Imh0dHA6Ly9jcmVhdGl2ZWNvbW1vbnMub3JnL25zIyIKICAgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIgogICB4bWxuczpzdmc9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIgogICB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciCiAgIHhtbG5zOnNvZGlwb2RpPSJodHRwOi8vc29kaXBvZGkuc291cmNlZm9yZ2UubmV0L0RURC9zb2RpcG9kaS0wLmR0ZCIKICAgeG1sbnM6aW5rc2NhcGU9Imh0dHA6Ly93d3cuaW5rc2NhcGUub3JnL25hbWVzcGFjZXMvaW5rc2NhcGUiCiAgIHdpZHRoPSI3OS4zNjI1NzkiCiAgIGhlaWdodD0iMjYuMDUyNDA0IgogICB2aWV3Qm94PSIwIDAgNzkuMzYyNTc5IDI2LjA1MjQwNCIKICAgdmVyc2lvbj0iMS4xIgogICBpZD0ic3ZnMiIKICAgaW5rc2NhcGU6dmVyc2lvbj0iMC45MSByMTM3MjUiCiAgIHNvZGlwb2RpOmRvY25hbWU9InViaXgtbG9nby5zdmciPgogIDxtZXRhZGF0YQogICAgIGlkPSJtZXRhZGF0YTIyIj4KICAgIDxyZGY6UkRGPgogICAgICA8Y2M6V29yawogICAgICAgICByZGY6YWJvdXQ9IiI+CiAgICAgICAgPGRjOmZvcm1hdD5pbWFnZS9zdmcreG1sPC9kYzpmb3JtYXQ+CiAgICAgICAgPGRjOnR5cGUKICAgICAgICAgICByZGY6cmVzb3VyY2U9Imh0dHA6Ly9wdXJsLm9yZy9kYy9kY21pdHlwZS9TdGlsbEltYWdlIiAvPgogICAgICAgIDxkYzp0aXRsZT5JbXBvcnRlZCBMYXllcnMgQ29weTwvZGM6dGl0bGU+CiAgICAgIDwvY2M6V29yaz4KICAgIDwvcmRmOlJERj4KICA8L21ldGFkYXRhPgogIDxzb2RpcG9kaTpuYW1lZHZpZXcKICAgICBwYWdlY29sb3I9IiNmZmZmZmYiCiAgICAgYm9yZGVyY29sb3I9IiM2NjY2NjYiCiAgICAgYm9yZGVyb3BhY2l0eT0iMSIKICAgICBvYmplY3R0b2xlcmFuY2U9IjEwIgogICAgIGdyaWR0b2xlcmFuY2U9IjEwIgogICAgIGd1aWRldG9sZXJhbmNlPSIxMCIKICAgICBpbmtzY2FwZTpwYWdlb3BhY2l0eT0iMCIKICAgICBpbmtzY2FwZTpwYWdlc2hhZG93PSIyIgogICAgIGlua3NjYXBlOndpbmRvdy13aWR0aD0iOTcyIgogICAgIGlua3NjYXBlOndpbmRvdy1oZWlnaHQ9Ijc0NiIKICAgICBpZD0ibmFtZWR2aWV3MjAiCiAgICAgc2hvd2dyaWQ9ImZhbHNlIgogICAgIGZpdC1tYXJnaW4tdG9wPSIwIgogICAgIGZpdC1tYXJnaW4tbGVmdD0iMCIKICAgICBmaXQtbWFyZ2luLXJpZ2h0PSIwIgogICAgIGZpdC1tYXJnaW4tYm90dG9tPSIwIgogICAgIGlua3NjYXBlOnpvb209IjMuNDI1IgogICAgIGlua3NjYXBlOmN4PSIzOS41MTU4NzEiCiAgICAgaW5rc2NhcGU6Y3k9IjEzLjA1NzA5NSIKICAgICBpbmtzY2FwZTp3aW5kb3cteD0iMCIKICAgICBpbmtzY2FwZTp3aW5kb3cteT0iMCIKICAgICBpbmtzY2FwZTp3aW5kb3ctbWF4aW1pemVkPSIwIgogICAgIGlua3NjYXBlOmN1cnJlbnQtbGF5ZXI9InN2ZzIiIC8+CiAgPCEtLSBHZW5lcmF0b3I6IFNrZXRjaCAzLjMuMiAoMTIwNDMpIC0gaHR0cDovL3d3dy5ib2hlbWlhbmNvZGluZy5jb20vc2tldGNoIC0tPgogIDx0aXRsZQogICAgIGlkPSJ0aXRsZTQiPkltcG9ydGVkIExheWVycyBDb3B5PC90aXRsZT4KICA8ZGVzYwogICAgIGlkPSJkZXNjNiI+Q3JlYXRlZCB3aXRoIFNrZXRjaC48L2Rlc2M+CiAgPGRlZnMKICAgICBpZD0iZGVmczgiIC8+CiAgPGcKICAgICBpZD0iUGFnZS0xIgogICAgIHNrZXRjaDp0eXBlPSJNU1BhZ2UiCiAgICAgc3R5bGU9ImZpbGw6bm9uZTtmaWxsLXJ1bGU6ZXZlbm9kZDtzdHJva2U6bm9uZTtzdHJva2Utd2lkdGg6MSIKICAgICB0cmFuc2Zvcm09InRyYW5zbGF0ZSgtMC40ODQxMjkwMywtMC41MDQ2OTIzMSkiPgogICAgPGcKICAgICAgIGlkPSJMRzotMTIwMC1FeHRyYS1zaG9ydC1DaHJvbWUiCiAgICAgICBza2V0Y2g6dHlwZT0iTVNBcnRib2FyZEdyb3VwIgogICAgICAgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTE1LC03KSIKICAgICAgIHN0eWxlPSJmaWxsOiNmZjVlMDAiPgogICAgICA8ZwogICAgICAgICBpZD0iTWVudS1CYXItMiIKICAgICAgICAgc2tldGNoOnR5cGU9Ik1TTGF5ZXJHcm91cCI+CiAgICAgICAgPGcKICAgICAgICAgICBpZD0iSW1wb3J0ZWQtTGF5ZXJzLUNvcHkiCiAgICAgICAgICAgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMTUsNykiCiAgICAgICAgICAgc2tldGNoOnR5cGU9Ik1TU2hhcGVHcm91cCI+CiAgICAgICAgICA8cGF0aAogICAgICAgICAgICAgZD0ibSAyMi40NTE2MTMsMTQuNjA5MDc3IGMgMCwzLjUxODMwOCAtMS4xOTU4NzEsNi40NzI3MzEgLTYuNjQwNTE2LDYuNDcyNzMxIC01LjQxODgzOSwwIC02LjY0MDUxNjMsLTIuOTU0NDIzIC02LjY0MDUxNjMsLTYuNDcyNzMxIGwgMCwtNy44Njg0MjMyIDIuMzM3NTQ4MywwIDAsNy44Njg0MjMyIGMgMCwyLjUyNTAxOSAwLjQ3ODQ1Miw0LjEwOTE5MiA0LjMwMjk2OCw0LjEwOTE5MiAzLjgyNTAzMiwwIDQuMzAyOTY4LC0xLjU4NDE3MyA0LjMwMjk2OCwtNC4xMDkxOTIgbCAwLC03Ljg2ODQyMzIgMi4zMzc1NDgsMCAwLDcuODY4NDIzMiIKICAgICAgICAgICAgIGlkPSJGaWxsLTEiCiAgICAgICAgICAgICBpbmtzY2FwZTpjb25uZWN0b3ItY3VydmF0dXJlPSIwIiAvPgogICAgICAgICAgPHBhdGgKICAgICAgICAgICAgIGQ9Im0gMzUuOTU0MDY0LDYuNzQwNjUzOCBjIDEuNjIwNjQ2LDAgNC41NDI0NTIsMC40Mjk0MDM5IDQuNTQyNDUyLDMuNTk4MjY5MiAwLDEuNDc3MjEyIC0wLjM0NTgwNiwxLjg1MzY1NCAtMC43OTY5MDMsMi42MzE5ODEgMC41NTc0MTksMC41OTA4ODUgMS40ODc0ODQsMS40MjMyMTEgMS40ODc0ODQsMy4zNTczNDYgMCwyLjQxNzAxOSAtMS40MzQzMjMsNC4zMjM2MzUgLTUuMjMzMDMzLDQuMzIzNjM1IGwgLTguNzEyMjU4LDAgMCwtMTMuOTExMjMxMiA4LjcxMjI1OCwwIDAsMCB6IG0gMCw1LjM0NDQ0MjIgYyAxLjI0ODUxNywwIDIuMjA0OTA0LC0wLjM3NjQ0MiAyLjIwNDkwNCwtMS40NzcyMTEgMCwtMS4yMDg3Njk2IC0wLjg3NjkwNCwtMS41MDQyMTE5IC0yLjIwNDkwNCwtMS41MDQyMTE5IGwgLTYuMzc0NzA5LDAgMCwyLjk4MTQyMjkgNi4zNzQ3MDksMCAwLDAgeiBtIDAsNi4yMDM3NjkgYyAxLjgwNjQ1MiwwIDIuODk1NDg0LC0wLjQwMjkyMyAyLjg5NTQ4NCwtMS43OTk2NTQgMCwtMS44MjYxMzQgLTEuMDM2Mzg3LC0yLjA0MTA5NiAtMi43ODkxNjEsLTIuMDQxMDk2IGwgLTYuNDgxMDMyLDAgMCwzLjg0MDc1IDYuMzc0NzA5LDAgMCwwIHoiCiAgICAgICAgICAgICBpZD0iRmlsbC0yIgogICAgICAgICAgICAgaW5rc2NhcGU6Y29ubmVjdG9yLWN1cnZhdHVyZT0iMCIgLz4KICAgICAgICAgIDxwYXRoCiAgICAgICAgICAgICBkPSJtIDQ2LjgyNzM1NSw2Ljc0MDY1MzggMi4zMzc1NDgsMCAwLDEzLjkxMTc1MDIgLTIuMzM3NTQ4LDAgMCwtMTMuOTExNzUwMiB6IgogICAgICAgICAgICAgaWQ9IkZpbGwtMyIKICAgICAgICAgICAgIGlua3NjYXBlOmNvbm5lY3Rvci1jdXJ2YXR1cmU9IjAiIC8+CiAgICAgICAgICA8cGF0aAogICAgICAgICAgICAgZD0ibSA2OS45NjE4MDYsMjAuNjUxODg1IC0zLjE4NzYxMywwIC00Ljk2NjcwOSwtNS42Mzk4ODUgLTUuMDQ3MjI2LDUuNjM5ODg1IC0zLjE4NzA5NywwIDYuNjEzNjc4LC03LjQxMjAyIC01LjcxMDQ1MiwtNi40OTkyMTEyIDMuMTA3MDk3LDAgNC4yMjQsNC43MjY1NTcyIDQuMzgyOTY4LC00LjcyNjU1NzIgMy4wMjc2MTIsMCAtNS44NDM2MTIsNi40OTkyMTEyIDYuNTg3MzU0LDcuNDEyMDIiCiAgICAgICAgICAgICBpZD0iRmlsbC00IgogICAgICAgICAgICAgaW5rc2NhcGU6Y29ubmVjdG9yLWN1cnZhdHVyZT0iMCIgLz4KICAgICAgICAgIDxwYXRoCiAgICAgICAgICAgICBkPSJtIDAuNDg0MTI5MDMsMC41MDQ2OTIzMSAyLjA2MTQxOTM3LDAgMCwyNi4wNTI0MDM2OSAtMi4wNjE0MTkzNywwIDAsLTI2LjA1MjQwMzY5IHoiCiAgICAgICAgICAgICBpZD0iRmlsbC01IgogICAgICAgICAgICAgaW5rc2NhcGU6Y29ubmVjdG9yLWN1cnZhdHVyZT0iMCIgLz4KICAgICAgICAgIDxwYXRoCiAgICAgICAgICAgICBkPSJtIDc3Ljc4NTgwNywwLjUwNDY5MjMxIDIuMDYwOTAzLDAgMCwyNi4wNTI0MDM2OSAtMi4wNjA5MDMsMCAwLC0yNi4wNTI0MDM2OSB6IgogICAgICAgICAgICAgaWQ9IkZpbGwtNiIKICAgICAgICAgICAgIGlua3NjYXBlOmNvbm5lY3Rvci1jdXJ2YXR1cmU9IjAiIC8+CiAgICAgICAgPC9nPgogICAgICA8L2c+CiAgICA8L2c+CiAgPC9nPgo8L3N2Zz4K
      mediatype: image/svg+xml
  install:
    spec:
      deployments:
        - name: ubix-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                name: ubix-operator
            strategy: {}
            template:
              metadata:
                labels:
                  name: ubix-operator
              spec:
                containers:
                  - command:
                      - /usr/local/bin/ao-logs
                      - /tmp/ansible-operator/runner
                      - stdout
                    image: registry.connect.redhat.com/ubixlabs/ubix-operator
                    imagePullPolicy: Always
                    name: ansible
                    resources: {}
                    volumeMounts:
                      - mountPath: /tmp/ansible-operator/runner
                        name: runner
                        readOnly: true
                  - env:
                      - name: WATCH_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.annotations['olm.targetNamespaces']
                      - name: POD_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                      - name: OPERATOR_NAME
                        value: ubix-operator
                      - name: ANSIBLE_GATHERING
                        value: explicit
                    image: registry.connect.redhat.com/ubixlabs/ubix-operator
                    imagePullPolicy: Always
                    name: operator
                    resources: {}
                    volumeMounts:
                      - mountPath: /tmp/ansible-operator/runner
                        name: runner
                serviceAccountName: ubix-operator
                volumes:
                  - emptyDir: {}
                    name: runner
      permissions:
        - rules:
            - apiGroups:
                - ''
              resources:
                - pods
                - services
                - services/finalizers
                - endpoints
                - persistentvolumeclaims
                - events
                - configmaps
                - secrets
              verbs:
                - '*'
            - apiGroups:
                - apps
              resources:
                - deployments
                - daemonsets
                - replicasets
                - statefulsets
              verbs:
                - '*'
            - apiGroups:
                - monitoring.coreos.com
              resources:
                - servicemonitors
              verbs:
                - get
                - create
            - apiGroups:
                - apps
              resourceNames:
                - ubix-operator
              resources:
                - deployments/finalizers
              verbs:
                - update
            - apiGroups:
                - ''
              resources:
                - pods
              verbs:
                - get
            - apiGroups:
                - apps
              resources:
                - replicasets
                - deployments
              verbs:
                - get
            - apiGroups:
                - ubixlabs.com
              resources:
                - '*'
              verbs:
                - '*'
          serviceAccountName: ubix-operator
    strategy: deployment
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: false
      type: AllNamespaces
  keywords:
    - data science
    - automation
    - big data
    - spark
  links:
    - name: Homepage
      url: https://ubixlabs.com/
  maintainers:
    - email: george.stoianov@ubixlabs.com
      name: George Stoianov
  maturity: alpha
  minKubeVersion: 1.11.0
  provider:
    name: Ubixlabs
  version: 0.0.1
