apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ubixes.ubixlabs.com
spec:
  group: ubixlabs.com
  names:
    kind: Ubix
    listKind: UbixList
    plural: ubixes
    singular: ubix
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          description: Ubix spec object
          properties:
            cassandra:
              properties:
                enable:
                  type: string
                image:
                  type: string
                imageTag:
                  type: string
              type: object
            defaultImageTag:
              type: string
            elasticsearch:
              properties:
                enable:
                  type: string
                image:
                  type: string
                imageTag:
                  type: string
              type: object
            hdfs:
              properties:
                datanodeImage:
                  type: string
                datanodeReplicas:
                  type: integer
                enable:
                  type: string
                namenodeImage:
                  type: string
                namenodeImageTag:
                  type: string
              type: object
            imageRegistry:
              type: string
            metastore:
              properties:
                enable:
                  type: string
                image:
                  type: string
                imageTag:
                  type: string
              type: object
            mongo:
              properties:
                enable:
                  type: string
                image:
                  type: string
                imageTag:
                  type: string
              type: object
            portal:
              properties:
                enable:
                  type: string
                image:
                  type: string
                imageTag:
                  type: string
              type: object
            postgres:
              properties:
                enable:
                  type: string
                image:
                  type: string
                imageTag:
                  type: string
              type: object
            spark:
              properties:
                enable:
                  type: string
                masterImage:
                  type: string
                masterImageTag:
                  type: string
                workerImage:
                  type: string
                workers:
                  type: integer
              type: object
            ubixDomain:
              type: string
            ubixNamespace:
              type: string
            ui:
              properties:
                enable:
                  type: string
                nginxImage:
                  type: string
                nginxImageTag:
                  type: string
                uxFrameImage:
                  type: string
                uxFrameImageTag:
                  type: string
              type: object
            workspaceManager:
              properties:
                enable:
                  type: string
                image:
                  type: string
                imageTag:
                  type: string
                sparkCoresMax:
                  type: string
              type: object
            zookeeper:
              properties:
                enable:
                  type: string
                image:
                  type: string
                imageTag:
                  type: string
              type: object
          type: object
        status:
          properties:
            conditions:
              type: array
          type: object
      type: object
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
