apiVersion: v1
kind: Pod
metadata:
  name: nvidia-test-01
  namespace: nvidia
spec:
  restartPolicy: OnFailure
  nodeSelector:
    # type: infra
    kubernetes.io/hostname: node3.sigma.cmri
  containers:
    - name: nttmec-gpu-test
      image: "registry.sigma.cmri/test/nttmec_cpu"
      env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: all
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "compute,utility"
        - name: NVIDIA_REQUIRE_CUDA
          value: "cuda>=5.0"
      command: ['tail']
      args: ["-f", "/dev/null"]
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        seLinuxOptions:
          type: nvidia_container_t