apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: interconnects.interconnectedcloud.github.io
spec:
  group: interconnectedcloud.github.io
  names:
    kind: Interconnect
    listKind: InterconnectList
    plural: interconnects
    singular: interconnect
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            addresses:
              description: Configuration of each address distribution and phasing
              items:
                description: address configuration
                properties:
                  distribution:
                    description: Treatment of traffic associated with the address
                    enum:
                      - balanced
                      - closest
                      - multicast
                    type: string
                  egressPhase:
                    description: Egress phase override for the address
                    maximum: 9
                    minimum: 0
                    type: integer
                  enableFallback:
                    description: Indicator for treatment of undeliverable messages
                    type: boolean
                  ingressPhase:
                    description: Ingress phase override for the address
                    maximum: 9
                    minimum: 0
                    type: integer
                  pattern:
                    description: A wildcarded pattern for address matching
                    type: string
                  prefix:
                    description: The address prefix for the configured setting
                    type: string
                  priority:
                    description: Priority assigned to address for inter router transfer
                    maximum: 9
                    minimum: 0
                    type: integer
                  waypoint:
                    description: Indicator for waypoint use
                    type: boolean
                type: object
              type: array
            autoLinks:
              items:
                properties:
                  address:
                    type: string
                  connection:
                    type: string
                  containerId:
                    type: string
                  direction:
                    type: string
                  externalPrefix:
                    type: string
                  fallback:
                    type: boolean
                  phase:
                    format: int32
                    type: integer
                required:
                  - address
                  - direction
                type: object
              type: array
            connectors:
              description: Configuration of each individual router connnector
              items:
                properties:
                  cost:
                    format: int32
                    type: integer
                  host:
                    type: string
                  name:
                    type: string
                  port:
                    format: int32
                    type: integer
                  routeContainer:
                    type: boolean
                  sslProfile:
                    type: string
                  verifyHostname:
                    description: Verify hostname of server when using TLS
                    type: boolean
                required:
                  - host
                  - port
                type: object
              type: array
            deploymentPlan:
              properties:
                image:
                  description: The image used for the interconnect deployment
                  type: string
                issuer:
                  description: The externally provided credentials
                  type: string
                livenessPort:
                  description: The liveness probe port number
                  type: integer
                placement:
                  description: The interconnect placement plan
                  enum:
                    - Any
                    - Every
                    - AntiAffinity
                    - Node
                  type: string
                resources:
                  properties:
                    limits:
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                      type: object
                    requests:
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                      type: object
                  type: object
                role:
                  description: The interconnect deployment role
                  enum:
                    - edge
                    - interior
                  type: string
                serviceType:
                  description: The type of service to create
                  type: string
                size:
                  description: The number of interconnect pods to deploy
                  maximum: 16
                  minimum: 1
                  type: integer
              type: object
            edgeConnectors:
              description: Configuration of each individual edge uplink connector
              items:
                properties:
                  cost:
                    format: int32
                    type: integer
                  host:
                    type: string
                  name:
                    type: string
                  port:
                    format: int32
                    type: integer
                  routeContainer:
                    description: Indicator for a router-broker connection
                    type: boolean
                  sslProfile:
                    type: string
                  verifyHostname:
                    description: Verify hostname of server when using TLS
                    type: boolean
                required:
                  - host
                  - port
                type: object
              type: array
            edgeListeners:
              description: Configuration of each individual inter edge listener
              items:
                description: interconnect listener configuration
                properties:
                  authenticatePeer:
                    description: Require incoming connections to authenticate
                    type: boolean
                  cost:
                    description: Cost metric for inter router connections
                    type: integer
                  expose:
                    type: boolean
                  host:
                    description: Host name
                    type: string
                  http:
                    description: Accept HTTP connections
                    type: boolean
                  name:
                    description: Listener name
                    type: string
                  port:
                    description: Port number
                    type: integer
                  routeContainer:
                    description: Indicator for a router-broker connection
                    type: boolean
                  saslMechanisms:
                    description: List of space separate SASL mechanisms to offer
                    type: string
                  sslProfile:
                    description: Name of the ssl profile to use
                    type: string
                type: object
              type: array
            interRouterConnectors:
              description: Configuration of each individual inter router connector
              items:
                properties:
                  cost:
                    format: int32
                    type: integer
                  host:
                    type: string
                  name:
                    type: string
                  port:
                    format: int32
                    type: integer
                  routeContainer:
                    type: boolean
                  sslProfile:
                    type: string
                  verifyHostname:
                    description: Verify hostname of server when using TLS
                    type: boolean
                required:
                  - host
                  - port
                type: object
              type: array
            interRouterListeners:
              description: Configuration of each individual inter router listener
              items:
                description: interconnect listener configuration
                properties:
                  authenticatePeer:
                    description: Require incoming connections to authenticate
                    type: boolean
                  cost:
                    description: Cost metric for inter router connections
                    type: integer
                  expose:
                    type: boolean
                  host:
                    description: Host name
                    type: string
                  http:
                    description: Accept HTTP connections
                    type: boolean
                  name:
                    description: Listener name
                    type: string
                  port:
                    description: Port number
                    type: integer
                  routeContainer:
                    description: Indicator for a router-broker connection
                    type: boolean
                  saslMechanisms:
                    description: List of space separate SASL mechanisms to offer
                    type: string
                  sslProfile:
                    description: Name of the ssl profile to use
                    type: string
                type: object
              type: array
            issuer:
              type: string
            linkRoutes:
              items:
                properties:
                  addExternalPrefix:
                    type: string
                  connection:
                    type: string
                  containerId:
                    type: string
                  direction:
                    type: string
                  pattern:
                    type: string
                  prefix:
                    type: string
                  removeExternalPrefix:
                    type: string
                type: object
              type: array
            listeners:
              description: Configuration of each individual interconnect listener
              items:
                description: interconnect listener configuration
                properties:
                  authenticatePeer:
                    description: Require incoming connections to authenticate
                    type: boolean
                  cost:
                    description: Cost metric for inter router connections
                    type: integer
                  expose:
                    type: boolean
                  host:
                    description: Host name
                    type: string
                  http:
                    description: Accept HTTP connections
                    type: boolean
                  name:
                    description: Listener name
                    type: string
                  port:
                    description: Port number
                    type: integer
                  role:
                    type: boolean
                  routeContainer:
                    description: Indicator for a router-broker connection
                    type: boolean
                  saslMechanisms:
                    description: List of space separate SASL mechanisms to offer
                    type: string
                  sslProfile:
                    description: Name of the ssl profile to use
                    type: string
                type: object
              minItems: 1
              type: array
            sslProfiles:
              items:
                properties:
                  caCert:
                    type: string
                  ciphers:
                    type: string
                  credentials:
                    type: string
                  generateCaCert:
                    type: boolean
                  generateCredentials:
                    type: boolean
                  mutualAuth:
                    type: boolean
                  name:
                    type: string
                  protocols:
                    type: string
                type: object
              type: array
            users:
              description: The name of a secret holding user and password details
              type: string
          type: object
        status:
          properties:
            conditions:
              description: Conditions keeps most recent interconnect conditions
              items:
                properties:
                  reason:
                    type: string
                  transitionTime:
                    format: date-time
                    type: object
                  type:
                    type: string
                required:
                  - type
                type: object
              type: array
            phase:
              type: string
            pods:
              items:
                type: string
              type: array
            revNumber:
              type: string
          required:
            - pods
            - conditions
          type: object
      required:
        - spec
  version: v1alpha1
