apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: kube-arangodb-crd
    helm.sh/chart: kube-arangodb-crd-0.4.2
    release: release-name
  name: arangobackuppolicies.backup.arangodb.com
spec:
  additionalPrinterColumns:
    - JSONPath: .spec.schedule
      description: Schedule
      name: Schedule
      type: string
    - JSONPath: .status.scheduled
      description: Scheduled
      name: Scheduled
      type: string
    - JSONPath: .status.message
      description: Message of the ArangoBackupPolicy object
      name: Message
      priority: 1
      type: string
  group: backup.arangodb.com
  names:
    kind: ArangoBackupPolicy
    listKind: ArangoBackupPolicyList
    plural: arangobackuppolicies
    shortNames:
      - arangobackuppolicy
      - arangobp
    singular: arangobackuppolicy
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
    - name: v1
      served: true
      storage: true
    - name: v1alpha
      served: true
      storage: false
