apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: kube-arangodb-crd
    helm.sh/chart: kube-arangodb-crd-0.4.2
    release: release-name
  name: arangobackups.backup.arangodb.com
spec:
  additionalPrinterColumns:
    - JSONPath: .spec.policyName
      description: Policy name
      name: Policy
      type: string
    - JSONPath: .spec.deployment.name
      description: Deployment name
      name: Deployment
      type: string
    - JSONPath: .status.backup.version
      description: Backup Version
      name: Version
      type: string
    - JSONPath: .status.backup.createdAt
      description: Backup Creation Timestamp
      name: Created
      type: string
    - JSONPath: .status.backup.sizeInBytes
      description: Backup Size in Bytes
      format: byte
      name: Size
      type: integer
    - JSONPath: .status.backup.numberOfDBServers
      description: Backup Number of the DB Servers
      name: DBServers
      type: integer
    - JSONPath: .status.state
      description: The actual state of the ArangoBackup
      name: State
      type: string
    - JSONPath: .status.message
      description: Message of the ArangoBackup object
      name: Message
      priority: 1
      type: string
  group: backup.arangodb.com
  names:
    kind: ArangoBackup
    listKind: ArangoBackupList
    plural: arangobackups
    shortNames:
      - arangobackup
    singular: arangobackup
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
    - name: v1
      served: true
      storage: true
    - name: v1alpha
      served: true
      storage: false
