apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: kube-arangodb-crd
    helm.sh/chart: kube-arangodb-crd-0.4.2
    release: release-name
  name: arangodeployments.database.arangodb.com
spec:
  group: database.arangodb.com
  names:
    kind: ArangoDeployment
    listKind: ArangoDeploymentList
    plural: arangodeployments
    shortNames:
      - arangodb
      - arango
    singular: arangodeployment
  scope: Namespaced
  version: v1
  versions:
    - name: v1
      served: true
      storage: true
    - name: v1alpha
      served: true
      storage: false
