apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  annotations:
    name.os.template.cnv.io/win10: Microsoft Windows 10
  selfLink: /apis/kubevirt.io/v1alpha3/namespaces/default/virtualmachines/win7
  resourceVersion: '413386'
  name: win7
  uid: 927a2619-7095-11e9-83a9-7ca23e90ca35
  creationTimestamp: '2019-05-07T06:58:52Z'
  generation: 1
  namespace: default
  labels:
    app: win7
    flavor.template.cnv.io/Custom: 'true'
    os.template.cnv.io/win10: 'true'
    template.cnv.ui: openshift_win2k12r2-generic-large
    vm.cnv.io/template: win2k12r2-generic-large
    workload.template.cnv.io/generic: 'true'
spec:
  dataVolumeTemplates:
    - metadata:
        creationTimestamp: null
        name: rootdisk-win7
      spec:
        pvc:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
          storageClassName: glusterfs-storage
        source:
          http:
            url: >-
              ftp://192.168.39.135/cn_windows_7_ultimate_with_sp1_x64_dvd_618537.iso
      status: {}
  running: true
  template:
    metadata:
      creationTimestamp: null
      labels:
        vm.cnv.io/name: win7
    spec:
      domain:
        clock:
          timer:
            hpet:
              present: false
            hyperv: {}
            pit:
              tickPolicy: delay
            rtc:
              tickPolicy: catchup
          utc: {}
        cpu:
          cores: 2
          sockets: 2
          threads: 1
        devices:
          disks:
            - bootOrder: 1
              disk:
                bus: sata
              name: rootdisk
          interfaces:
            - bridge: {}
              model: e1000e
              name: nic0
        features:
          acpi: {}
          apic: {}
          hyperv:
            relaxed: {}
            spinlocks:
              spinlocks: 8191
            vapic: {}
        machine:
          type: ''
        resources:
          requests:
            memory: 6G
      networks:
        - name: nic0
          pod: {}
      terminationGracePeriodSeconds: 0
      volumes:
        - dataVolume:
            name: rootdisk-win7
          name: rootdisk
status:
  conditions:
    - lastProbeTime: null
      lastTransitionTime: '2019-05-07T06:58:52Z'
      message: >-
        Failed to create DataVolume: admission webhook
        "datavolume-create-validator.cdi.kubevirt.io" denied the request: 
        spec.source Invalid source URL scheme:
        ftp://192.168.39.135/cn_windows_7_ultimate_with_sp1_x64_dvd_618537.iso
      reason: FailedDelete
      status: 'True'
      type: Failure
