version: '3'
services:

  dbz-connect:
    # image: dbz-oracle-12-2:wzh
    # image: dbz-oracle-11-2:wzh
    image: dbz-oracle:wzh
    environment:
      GROUP_ID: 2
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      BOOTSTRAP_SERVERS: "172.19.16.8:9092"
      LD_LIBRARY_PATH: "/instant_client"
    restart: unless-stopped
    ports:
      - "0.0.0.0:5005:5005"
      - "0.0.0.0:8778:8778"
      - "0.0.0.0:9092:9092"
      - "0.0.0.0:9779:9779"
    networks:
      - esnet


networks:
  esnet: