version: '3'
services:

  dbz-connect:
    # image: dbz-oracle-12-2:wzh
    # image: dbz-oracle-11-2:wzh
    image: dbz-oracle:wzh
    environment:
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      BOOTSTRAP_SERVERS: "10.88.104.225:9292"
      LD_LIBRARY_PATH: "/instant_client"
      KAFKA_DEBUG: "true"
      DEBUG_SUSPEND_FLAG: "n"
    restart: unless-stopped
    ports:
      - "0.0.0.0:5005:5005"
      - "0.0.0.0:8778:8778"
      - "0.0.0.0:9092:9092"
      - "0.0.0.0:9779:9779"
    networks:
      - esnet

networks:
  esnet: