version: '3'
services:
  teiid:
    image: jboss/teiid
    environment:
      - cluster.name=docker-cluster
      - node.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 0.0.0.0:8080:8080
      - 0.0.0.0:9990:9990
      - 0.0.0.0:31000:31000
      - 0.0.0.0:35432:35432
    networks:
      - teiid

networks:
  teiid: