version: '3'
services:
  teiid:
    image: jboss/teiid
    environment:
      - cluster.name=docker-cluster
      - node.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 0.0.0.0:9200:9200
    networks:
      - teiid

networks:
  teiid: