apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: joget.app.joget.com
spec:
  group: app.joget.com
  names:
    kind: Joget
    listKind: JogetList
    plural: joget
    singular: joget
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
