---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: demo
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      demo: wzh
  template:
    metadata:
      labels:
        demo: wzh
    spec:
      restartPolicy: Always
      containers:
        - resources:
            requests:
              cpu: 100m
              memory: 256Mi
          name: demo
          env:
            - name: STATS_PORT
              value: '19360'
          imagePullPolicy: IfNotPresent
          image: registry.redhat.ren:5443/docker.io/tomcat:latest
---
kind: Service
apiVersion: v1
metadata:
  name: demo
  namespace: demo
  labels:
    demo: wzh
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    demo: wzh
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: demo
  namespace: demo
  annotations:
    wzh-external-tcp-port: "18080"
spec:
  to:
    kind: Service
    name: demo
  port:
    targetPort: 8080
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: None
