apiVersion: v1
kind: Service
metadata:
  annotations:
    loadbalancer.alauda.io/bind: '[{"container_port":3306,"protocol":"tcp","name":"{{NGINX}}","port":13306}]'
  labels:
    service.alauda.io/name: hadoopmysql
  name: hadoopmysql
  namespace: {{REGION}}
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    component: hadoopmysql
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hadoopmysql
  namespace: {{REGION}}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: hadoopmysql
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        service.alauda.io/name: hadoopmysql
        component: hadoopmysql
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        name: hadoopmysql
        image: {{REGISTRY}}/mysql:5.7
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "1"
            memory: "2G"
        volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: "hive-mysql"
            readOnly: false
      volumes:
        - hostPath:
            path: /alauda_data/hive_mysql
            type: Directory
          name: "hive-mysql"
      nodeSelector:
        ip: "11.11.157.145"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: namenode
  namespace: {{REGION}}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: namenode
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        service.alauda.io/name: namenode
        component: namenode
    spec:
      containers:
      - env:
        - name: NODE_IPS
          value: "{{NODE_IPS}}"
        - name: NAME_NODE_ADDR
          value: "{{NAME_NODE_ADDR}}"
        - name: SECOND_NAME_NODE_ADDR
          value: "{{SECOND_NAME_NODE_ADDR}}"
        - name: NAME_NODE_PORT
          value: "9000"
        - name: SERVER_ROLE
          value: "nn"
        - name: FORMAT_NAMENODE
          value: "true"
        - name: START_YARN
          value: "true"
        - name: ALB_ADDR
          value: "{{ALB_IP}}"
        - name: HIVE_MYSQL_ADDR
          value: "{{HIVE_MYSQL_ADDR}}"
        - name: HIVE_MYSQL_PORT
          value: "13306"
        - name: HADOOP_HEAPSIZE
          value: "4096"
        name: namenode
        image: {{REGISTRY}}/hadoop:wzh
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "2"
            memory: "4G"
        volumeMounts:
          - mountPath: "/data"
            name: "hadoop-data"
            readOnly: false
      volumes:
        - hostPath:
            path: /alauda_data/hadoop_data
            type: Directory
          name: "hadoop-data"
      hostNetwork: true
      nodeSelector:
        ip: "11.11.157.145"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: secondnamenode
  namespace: {{REGION}}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: secondnamenode
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        service.alauda.io/name: secondnamenode
        component: secondnamenode
    spec:
      containers:
      - env:
        - name: NODE_IPS
          value: "{{NODE_IPS}}"
        - name: NAME_NODE_ADDR
          value: "{{NAME_NODE_ADDR}}"
        - name: SECOND_NAME_NODE_ADDR
          value: "{{SECOND_NAME_NODE_ADDR}}"
        - name: NAME_NODE_PORT
          value: "9000"
        - name: SERVER_ROLE
          value: "sn"
        - name: FORMAT_NAMENODE
          value: "true"
        - name: START_YARN
          value: "true"
        - name: ALB_ADDR
          value: "{{ALB_IP}}"
        - name: HADOOP_HEAPSIZE
          value: "4096"
        name: namenode
        image: {{REGISTRY}}/hadoop:wzh
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "2"
            memory: "4G"
        volumeMounts:
          - mountPath: "/data"
            name: "hadoop-data"
            readOnly: false
      volumes:
        - hostPath:
            path: /alauda_data/hadoop_data
            type: Directory
          name: "hadoop-data"
      hostNetwork: true
      nodeSelector:
        ip: "11.11.157.146"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: datanode1
  namespace: {{REGION}}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: datanode1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        service.alauda.io/name: datanode1
        component: datanode1
    spec:
      containers:
      - env:
        - name: NODE_IPS
          value: "{{NODE_IPS}}"
        - name: NAME_NODE_ADDR
          value: "{{NAME_NODE_ADDR}}"
        - name: SECOND_NAME_NODE_ADDR
          value: "{{SECOND_NAME_NODE_ADDR}}"
        - name: NAME_NODE_PORT
          value: "9000"
        - name: SERVER_ROLE
          value: "dn"
        - name: START_YARN
          value: "true"
        - name: HADOOP_HEAPSIZE
          value: "4096"
        name: datanode
        image: {{REGISTRY}}/hadoop:wzh
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "2"
            memory: 4G
        volumeMounts:
          - mountPath: "/data"
            name: "hadoop-data"
            readOnly: false
      volumes:
        - hostPath:
            path: /alauda_data/hadoop_data
            type: Directory
          name: "hadoop-data"
      hostNetwork: true
      nodeSelector:
        ip: "11.11.157.147"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: datanode2
  namespace: {{REGION}}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: datanode2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        service.alauda.io/name: datanode2
        component: datanode2
    spec:
      containers:
      - env:
        - name: NODE_IPS
          value: "{{NODE_IPS}}"
        - name: NAME_NODE_ADDR
          value: "{{NAME_NODE_ADDR}}"
        - name: SECOND_NAME_NODE_ADDR
          value: "{{SECOND_NAME_NODE_ADDR}}"
        - name: NAME_NODE_PORT
          value: "9000"
        - name: SERVER_ROLE
          value: "dn"
        - name: START_YARN
          value: "true"
        - name: HADOOP_HEAPSIZE
          value: "4096"
        name: datanode
        image: {{REGISTRY}}/hadoop:wzh
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "2"
            memory: 4G
        volumeMounts:
          - mountPath: "/data"
            name: "hadoop-data"
            readOnly: false
      volumes:
        - hostPath:
            path: /alauda_data/hadoop_data
            type: Directory
          name: "hadoop-data"
      hostNetwork: true
      nodeSelector:
        ip: "11.11.157.148"
---
