version: '3.6'
services:
  elasticsearch:
    image: elasticsearch:es_ai
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - node.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 0.0.0.0:9200:9200
    networks:
      - esnet
  
  elasticsearch2:
    image: elasticsearch:es_ai
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - node.name=elasticsearch2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet
    depends_on:
      - elasticsearch
      
  elasticsearch3:
    image: elasticsearch:es_ai
    container_name: elasticsearch3
    environment:
      - cluster.name=docker-cluster
      - node.name=elasticsearch3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata3:/usr/share/elasticsearch/data
    networks:
      - esnet
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.3.1
    container_name: kibana
    environment:
      - elasticsearch.url=http://elasticsearch:9200
    ports:
      - 0.0.0.0:5601:5601
    networks:
      - esnet
    depends_on:
      - elasticsearch
      - elasticsearch2
      - elasticsearch3

  elasticsearch_hq:
    image: elastichq/elasticsearch-hq 
    container_name: elasticsearch-hq
    environment:
      - HQ_DEFAULT_URL=http://elasticsearch:9200
    ports:
      - 0.0.0.0:5000:5000
    networks:
      - esnet
    depends_on:
      - elasticsearch
      - elasticsearch2
      - elasticsearch3

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  esdata3:
    driver: local


networks:
  esnet: