---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: flume
  namespace: {{REGION}}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: flume
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        service.alauda.io/name: flume
        component: flume
    spec:
      containers:
      - env:
        - name: NODE_IPS
          value: "{{NODE_IPS}}"
        - name: NAME_NODE_ADDR
          value: "{{NAME_NODE_ADDR}}"
        - name: SECOND_NAME_NODE_ADDR
          value: "{{SECOND_NAME_NODE_ADDR}}"
        - name: NAME_NODE_PORT
          value: "9000"
        - name: SERVER_ROLE
          value: "flume"
        - name: START_YARN
          value: "true"
        - name: HIVE_MYSQL_ADDR
          value: "{{HIVE_MYSQL_ADDR}}"
        - name: HIVE_MYSQL_PORT
          value: "3306"
        - name: HADOOP_HEAPSIZE
          value: "16348"
        - name: YARN_DIR
          value: "/data/yarn"
        - name: DATA_DIR
          value: "/data/hdfs/dn,/data2/hdfs/dn"
        - name: NAME_DIR
          value: "/data/hdfs/nn"
        - name: TMP_DIR
          value: "/data/hdfs/tmp"
        name: flume
        image: {{REGISTRY}}/a6-pro/cdh:wzh
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "6"
            memory: 24G
        volumeMounts:
          - mountPath: "/data"
            name: "hadoop-data"
            readOnly: false
          - mountPath: "/data2"
            name: "hadoop-data2"
            readOnly: false
      volumes:
        - hostPath:
            path: /alauda_data/data
            type: Directory
          name: "hadoop-data"
        - hostPath:
            path: /alauda_data/data2
            type: Directory
          name: "hadoop-data2"
      hostNetwork: true
      nodeSelector:
        ip: "11.11.157.209"
---