apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: robinclusters.robin.io
spec:
  additionalPrinterColumns:
    - JSONPath: .status.phase
      description: State of the robin cluster
      name: Phase
      type: string
  group: robin.io
  names:
    kind: RobinCluster
    listKind: RobinClusterList
    plural: robinclusters
    singular: robincluster
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            host_type:
              type: string
            image_provisioner:
              type: string
            image_robin:
              type: string
            image_version:
              type: string
            k8s_provider:
              type: string
            node_selector:
              type: string
            options:
              type: object
            source:
              type: string
            storage_disks:
              type: string
          type: object
        status:
          properties:
            connect_command:
              type: string
            get_robin_client:
              type: string
            master_ip:
              type: string
            phase:
              type: string
            pod_status:
              type: array
            robin_node_status:
              type: array
          type: object
  version: v1alpha1
