channels:
- currentCSV: openshifttemplateservicebrokeroperator.4.1.27-201912030019
  name: stable
- currentCSV: openshifttemplateservicebrokeroperator.4.2.11-201912100122
  name: '4.2'
- currentCSV: openshifttemplateservicebrokeroperator.4.2.11-201912100122-s390x
  name: 4.2-s390x
defaultChannel: '4.2'
packageName: openshifttemplateservicebroker
