apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hadoopmysql
  namespace: {{REGION}}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: hadoopmysql
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        service.alauda.io/name: hadoopmysql
        component: hadoopmysql
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "hive"
        name: hadoopmysql
        image: {{REGISTRY}}/a6-pro/mysql:5.7
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "1"
            memory: "2G"
        volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: "hive-mysql"
            readOnly: false
      volumes:
        - hostPath:
            path: /alauda_data/data/hive_mysql
            type: Directory
          name: "hive-mysql"
      hostNetwork: true
      nodeSelector:
        ip: "11.11.157.192"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: namenode
  namespace: {{REGION}}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: namenode
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        service.alauda.io/name: namenode
        component: namenode
    spec:
      containers:
      - env:
        - name: NODE_IPS
          value: "{{NODE_IPS}}"
        - name: NAME_NODE_ADDR
          value: "{{NAME_NODE_ADDR}}"
        - name: SECOND_NAME_NODE_ADDR
          value: "{{SECOND_NAME_NODE_ADDR}}"
        - name: NAME_NODE_PORT
          value: "9000"
        - name: SERVER_ROLE
          value: "nn"
        - name: FORMAT_NAMENODE
          value: "true"
        - name: START_YARN
          value: "true"
        - name: ALB_ADDR
          value: "{{ALB_IP}}"
        - name: HIVE_MYSQL_ADDR
          value: "11.11.157.192"
        - name: HIVE_MYSQL_PORT
          value: "3306"
        - name: HADOOP_HEAPSIZE
          value: "16348"
        name: namenode
        image: {{REGISTRY}}/a6-pro/hadoop:wzh
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "6"
            memory: "24G"
        volumeMounts:
          - mountPath: "/data"
            name: "hadoop-data"
            readOnly: false
      volumes:
        - hostPath:
            path: /alauda_data/data
            type: Directory
          name: "hadoop-data"
      hostNetwork: true
      nodeSelector:
        ip: "11.11.157.192"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: secondnamenode
  namespace: {{REGION}}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: secondnamenode
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        service.alauda.io/name: secondnamenode
        component: secondnamenode
    spec:
      containers:
      - env:
        - name: NODE_IPS
          value: "{{NODE_IPS}}"
        - name: NAME_NODE_ADDR
          value: "{{NAME_NODE_ADDR}}"
        - name: SECOND_NAME_NODE_ADDR
          value: "{{SECOND_NAME_NODE_ADDR}}"
        - name: NAME_NODE_PORT
          value: "9000"
        - name: SERVER_ROLE
          value: "sn"
        - name: FORMAT_NAMENODE
          value: "true"
        - name: START_YARN
          value: "true"
        - name: ALB_ADDR
          value: "{{ALB_IP}}"
        - name: HADOOP_HEAPSIZE
          value: "16348"
        name: namenode
        image: {{REGISTRY}}/a6-pro/hadoop:wzh
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "6"
            memory: "24G"
        volumeMounts:
          - mountPath: "/data"
            name: "hadoop-data"
            readOnly: false
      volumes:
        - hostPath:
            path: /alauda_data/data
            type: Directory
          name: "hadoop-data"
      hostNetwork: true
      nodeSelector:
        ip: "11.11.157.193"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: datanode1
  namespace: {{REGION}}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: datanode1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        service.alauda.io/name: datanode1
        component: datanode1
    spec:
      containers:
      - env:
        - name: NODE_IPS
          value: "{{NODE_IPS}}"
        - name: NAME_NODE_ADDR
          value: "{{NAME_NODE_ADDR}}"
        - name: SECOND_NAME_NODE_ADDR
          value: "{{SECOND_NAME_NODE_ADDR}}"
        - name: NAME_NODE_PORT
          value: "9000"
        - name: SERVER_ROLE
          value: "dn"
        - name: START_YARN
          value: "true"
        - name: HADOOP_HEAPSIZE
          value: "16348"
        - name: DATA_DIR
          value: "/data/hdfs,/data2/hdfs"
        name: datanode
        image: {{REGISTRY}}/a6-pro/hadoop:wzh
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "6"
            memory: 24G
        volumeMounts:
          - mountPath: "/data"
            name: "hadoop-data"
            readOnly: false
          - mountPath: "/data2"
            name: "hadoop-data2"
            readOnly: false
      volumes:
        - hostPath:
            path: /alauda_data/data
            type: Directory
          name: "hadoop-data"
        - hostPath:
            path: /alauda_data/data2
            type: Directory
          name: "hadoop-data2"
      hostNetwork: true
      nodeSelector:
        ip: "11.11.157.204"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: datanode2
  namespace: {{REGION}}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: datanode2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        service.alauda.io/name: datanode2
        component: datanode2
    spec:
      containers:
      - env:
        - name: NODE_IPS
          value: "{{NODE_IPS}}"
        - name: NAME_NODE_ADDR
          value: "{{NAME_NODE_ADDR}}"
        - name: SECOND_NAME_NODE_ADDR
          value: "{{SECOND_NAME_NODE_ADDR}}"
        - name: NAME_NODE_PORT
          value: "9000"
        - name: SERVER_ROLE
          value: "dn"
        - name: START_YARN
          value: "true"
        - name: HADOOP_HEAPSIZE
          value: "16348"
        - name: DATA_DIR
          value: "/data/hdfs,/data2/hdfs"
        name: datanode
        image: {{REGISTRY}}/a6-pro/hadoop:wzh
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "6"
            memory: 24G
        volumeMounts:
          - mountPath: "/data"
            name: "hadoop-data"
            readOnly: false
          - mountPath: "/data2"
            name: "hadoop-data2"
            readOnly: false
      volumes:
        - hostPath:
            path: /alauda_data/data
            type: Directory
          name: "hadoop-data"
        - hostPath:
            path: /alauda_data/data2
            type: Directory
          name: "hadoop-data2"
      hostNetwork: true
      nodeSelector:
        ip: "11.11.157.205"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: datanode3
  namespace: {{REGION}}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: datanode3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        service.alauda.io/name: datanode3
        component: datanode3
    spec:
      containers:
      - env:
        - name: NODE_IPS
          value: "{{NODE_IPS}}"
        - name: NAME_NODE_ADDR
          value: "{{NAME_NODE_ADDR}}"
        - name: SECOND_NAME_NODE_ADDR
          value: "{{SECOND_NAME_NODE_ADDR}}"
        - name: NAME_NODE_PORT
          value: "9000"
        - name: SERVER_ROLE
          value: "dn"
        - name: START_YARN
          value: "true"
        - name: HADOOP_HEAPSIZE
          value: "16348"
        - name: DATA_DIR
          value: "/data/hdfs,/data2/hdfs"
        name: datanode
        image: {{REGISTRY}}/a6-pro/hadoop:wzh
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "6"
            memory: 24G
        volumeMounts:
          - mountPath: "/data"
            name: "hadoop-data"
            readOnly: false
          - mountPath: "/data2"
            name: "hadoop-data2"
            readOnly: false
      volumes:
        - hostPath:
            path: /alauda_data/data
            type: Directory
          name: "hadoop-data"
        - hostPath:
            path: /alauda_data/data2
            type: Directory
          name: "hadoop-data2"
      hostNetwork: true
      nodeSelector:
        ip: "11.11.157.206"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: datanode4
  namespace: {{REGION}}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: datanode4
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        service.alauda.io/name: datanode4
        component: datanode4
    spec:
      containers:
      - env:
        - name: NODE_IPS
          value: "{{NODE_IPS}}"
        - name: NAME_NODE_ADDR
          value: "{{NAME_NODE_ADDR}}"
        - name: SECOND_NAME_NODE_ADDR
          value: "{{SECOND_NAME_NODE_ADDR}}"
        - name: NAME_NODE_PORT
          value: "9000"
        - name: SERVER_ROLE
          value: "dn"
        - name: START_YARN
          value: "true"
        - name: HADOOP_HEAPSIZE
          value: "16348"
        - name: DATA_DIR
          value: "/data/hdfs,/data2/hdfs"
        name: datanode
        image: {{REGISTRY}}/a6-pro/hadoop:wzh
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "6"
            memory: 24G
        volumeMounts:
          - mountPath: "/data"
            name: "hadoop-data"
            readOnly: false
          - mountPath: "/data2"
            name: "hadoop-data2"
            readOnly: false
      volumes:
        - hostPath:
            path: /alauda_data/data
            type: Directory
          name: "hadoop-data"
        - hostPath:
            path: /alauda_data/data2
            type: Directory
          name: "hadoop-data2"
      hostNetwork: true
      nodeSelector:
        ip: "11.11.157.207"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: datanode5
  namespace: {{REGION}}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: datanode5
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        service.alauda.io/name: datanode5
        component: datanode5
    spec:
      containers:
      - env:
        - name: NODE_IPS
          value: "{{NODE_IPS}}"
        - name: NAME_NODE_ADDR
          value: "{{NAME_NODE_ADDR}}"
        - name: SECOND_NAME_NODE_ADDR
          value: "{{SECOND_NAME_NODE_ADDR}}"
        - name: NAME_NODE_PORT
          value: "9000"
        - name: SERVER_ROLE
          value: "dn"
        - name: START_YARN
          value: "true"
        - name: HADOOP_HEAPSIZE
          value: "16348"
        - name: DATA_DIR
          value: "/data/hdfs,/data2/hdfs"
        name: datanode
        image: {{REGISTRY}}/a6-pro/hadoop:wzh
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "6"
            memory: 24G
        volumeMounts:
          - mountPath: "/data"
            name: "hadoop-data"
            readOnly: false
          - mountPath: "/data2"
            name: "hadoop-data2"
            readOnly: false
      volumes:
        - hostPath:
            path: /alauda_data/data
            type: Directory
          name: "hadoop-data"
        - hostPath:
            path: /alauda_data/data2
            type: Directory
          name: "hadoop-data2"
      hostNetwork: true
      nodeSelector:
        ip: "11.11.157.209"
---
