version: '3'
services:

  teiid-master:
    image: teiid:wzh
    environment:
      SERVER_ROLE: master
      MASTER_ADDR: "teiid-master"
    ports:
      - 0.0.0.0:18080:8080
      - 0.0.0.0:9990:9990
      - 0.0.0.0:31000:31000
      - 0.0.0.0:35432:35432
    networks:
      - teiid



networks:
  teiid: