apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mariadbsizes.mariadb.com
spec:
  group: mariadb.com
  names:
    kind: MariaDBSize
    plural: mariadbsizes
    shortNames:
      - mdbsz
    singular: mariadbsize
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            cluster:
              properties:
                annotations:
                  additionalProperties:
                    type: string
                  type: object
                imagePullSecret:
                  type: string
                imageRepo:
                  pattern: '[-a-zA-Z0-9@:%._\+~#=/]+'
                  type: string
                labels:
                  additionalProperties:
                    type: string
                  type: object
                nodeGroup:
                  type: string
                topology:
                  enum:
                    - standalone
                    - masterslave
                    - galera
                    - columnstore-standalone
                    - columnstore
                  type: string
            columnstore:
              properties:
                image:
                  pattern: '[-a-zA-Z0-9@:%._\+~#=/]+'
                  type: string
                numBlocksPct:
                  pattern: ^[0-9]+(E|Ei|P|Pi|T|Ti|G|Gi|M|Mi|K|Ki)?
                  type: string
                pm:
                  properties:
                    replicas:
                      minimum: 1
                      type: integer
                totalUmMemory:
                  pattern: ^[0-9]+(E|Ei|P|Pi|T|Ti|G|Gi|M|Mi|K|Ki)?
                  type: string
                um:
                  properties:
                    replicas:
                      minimum: 1
                      type: integer
            maxscale:
              properties:
                annotations:
                  additionalProperties:
                    type: string
                  type: object
                image:
                  pattern: '[-a-zA-Z0-9@:%._\+~#=/]+'
                  type: string
                labels:
                  additionalProperties:
                    type: string
                  type: object
                ports:
                  properties:
                    readonly:
                      maximum: 65535
                      minimum: 1
                      type: integer
                    readwrite:
                      maximum: 65535
                      minimum: 1
                      type: integer
                replicas:
                  minimum: 1
                  type: integer
                resources:
                  properties:
                    limits:
                      properties:
                        cpu:
                          pattern: ^([0-9])(m?|\.[0-9]{1,3})
                          type: string
                        memory:
                          pattern: ^[0-9]+(E|Ei|P|Pi|T|Ti|G|Gi|M|Mi|K|Ki)?
                          type: string
                    requests:
                      properties:
                        cpu:
                          pattern: ^([0-9])(m?|\.[0-9]{1,3})
                          type: string
                        memory:
                          pattern: ^[0-9]+(E|Ei|P|Pi|T|Ti|G|Gi|M|Mi|K|Ki)?
                          type: string
            server:
              properties:
                annotations:
                  additionalProperties:
                    type: string
                  type: object
                image:
                  pattern: '[-a-zA-Z0-9@:%._\+~#=/]+'
                  type: string
                labels:
                  additionalProperties:
                    type: string
                  type: object
                port:
                  maximum: 65535
                  minimum: 1
                  type: integer
                replicas:
                  minimum: 1
                  type: integer
                resources:
                  properties:
                    limits:
                      properties:
                        cpu:
                          pattern: ^([0-9])(m?|\.[0-9]{1,3})
                          type: string
                        memory:
                          pattern: ^[0-9]+(E|Ei|P|Pi|T|Ti|G|Gi|M|Mi|K|Ki)?
                          type: string
                    requests:
                      properties:
                        cpu:
                          pattern: ^([0-9])(m?|\.[0-9]{1,3})
                          type: string
                        memory:
                          pattern: ^[0-9]+(E|Ei|P|Pi|T|Ti|G|Gi|M|Mi|K|Ki)?
                          type: string
                storage:
                  properties:
                    class:
                      type: string
                    size:
                      pattern: ^[0-9]+(\.[0-9]+)?(E|Ei|P|Pi|T|Ti|G|Gi|M|Mi|K|Ki|m)?
                      type: string
                users:
                  properties:
                    admin:
                      properties:
                        password:
                          type: string
                        username:
                          type: string
                    replication:
                      properties:
                        password:
                          type: string
                        username:
                          type: string
            statestore:
              properties:
                image:
                  pattern: '[-a-zA-Z0-9@:%._\+~#=/]+'
                  type: string
        status:
          properties:
            registered:
              type: boolean
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
