apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: openunisons.openunison.tremolo.io
spec:
  group: openunison.tremolo.io
  names:
    kind: OpenUnison
    plural: openunisons
    shortNames:
      - ou
    singular: openunison
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            activemq_image:
              type: string
            dest_secret:
              type: string
            enable_activemq:
              type: boolean
            hosts:
              items:
                properties:
                  ingress_name:
                    type: string
                  names:
                    items:
                      properties:
                        env_var:
                          type: string
                        name:
                          type: string
                      type: object
                    type: array
                  node_selectors:
                    items:
                      properties:
                        name:
                          type: string
                        value:
                          type: string
                      type: object
                    type: array
                  secret_name:
                    type: string
                type: object
              type: array
            image:
              type: string
            key_store:
              properties:
                key_pairs:
                  properties:
                    create_keypair_template:
                      items:
                        properties:
                          name:
                            type: string
                          value:
                            type: string
                        type: object
                      type: array
                    keys:
                      items:
                        properties:
                          create_data:
                            properties:
                              ca_cert:
                                type: boolean
                              key_size:
                                type: integer
                              secret_info:
                                properties:
                                  cert_name:
                                    type: string
                                  key_name:
                                    type: string
                                  type_of_secret:
                                    type: string
                                type: object
                              server_name:
                                type: string
                              sign_by_k8s_ca:
                                type: boolean
                              subject_alternative_names:
                                items:
                                  type: string
                                type: array
                            type: object
                          import_into_ks:
                            enum:
                              - keypair
                              - certificate
                              - none
                            type: string
                          name:
                            type: string
                          replace_if_exists:
                            type: boolean
                          tls_secret_name:
                            type: string
                        type: object
                      type: array
                  type: object
                static_keys:
                  items:
                    properties:
                      name:
                        type: string
                      version:
                        type: integer
                    type: object
                  type: array
                trusted_certificates:
                  items:
                    properties:
                      name:
                        type: string
                      pem_data:
                        type: string
                    type: object
                  type: array
              type: object
            non_secret_data:
              items:
                properties:
                  name:
                    type: string
                  value:
                    type: string
                type: object
              type: array
            openshift:
              properties:
                builder_image:
                  type: string
                git:
                  properties:
                    branch:
                      type: string
                    dir:
                      type: string
                    repo:
                      type: string
                  type: object
              type: object
            openunison_network_configuration:
              properties:
                activemq_dir:
                  type: string
                allow_un_escaped_chars:
                  type: string
                allowed_client_names:
                  items:
                    type: string
                  type: array
                allowed_tls_protocols:
                  items:
                    type: string
                  type: array
                ciphers:
                  items:
                    type: string
                  type: array
                client_auth:
                  type: string
                context_root:
                  type: string
                disable_http2:
                  type: boolean
                error_pages:
                  items:
                    properties:
                      code:
                        type: integer
                      location:
                        type: string
                    type: object
                  type: array
                force_to_lower_case:
                  type: boolean
                force_to_secure:
                  type: boolean
                open_external_port:
                  type: integer
                open_port:
                  type: integer
                path_to_deployment:
                  type: string
                path_to_env_file:
                  type: string
                quartz_dir:
                  type: string
                redirect_to_context_root:
                  type: boolean
                secure_external_port:
                  type: integer
                secure_key_alias:
                  type: string
                secure_port:
                  type: integer
                welecome_pages:
                  items:
                    type: string
                  type: array
              type: object
            replicas:
              type: integer
            run_sql:
              type: string
            saml_remote_idp:
              items:
                properties:
                  mapping:
                    properties:
                      encryption_cert_alias:
                        type: string
                      entity_id:
                        type: string
                      logout_url:
                        type: string
                      post_url:
                        type: string
                      redirect_url:
                        type: string
                      signing_cert_alis:
                        type: string
                    type: object
                  source:
                    properties:
                      url:
                        type: string
                      xml:
                        type: string
                    type: object
                type: object
              type: array
            secret_data:
              items:
                type: string
              type: array
            source_secret:
              type: string
  version: v1
  versions:
    - name: v1
      served: true
      storage: true
status:
  acceptedNames:
    kind: ''
    plural: ''
  conditions: []
  storedVersions: []
