version: '3'
services:

  oracledb1:
    image: oracle-11g:wzh.11.2.0.4.cd_location
    restart: unless-stopped
    shm_size: '2gb'
    # ports:
    #   - "0.0.0.0:1521:1521"
    networks:
      - teiid
  
  oracledb2:
    image: oracle-11g:wzh.11.2.0.4.cd_location
    restart: unless-stopped
    shm_size: '2gb'
    # ports:
    #   - "0.0.0.0:1521:1521"
    networks:
      - teiid


  teiid-master:
    image: teiid:wzh
    environment:
      SERVER_ROLE: master
      MASTER_ADDR: "teiid-master"
    ports:
      - 0.0.0.0:8080:8080
      - 0.0.0.0:9990:9990
      - 0.0.0.0:31000:31000
      - 0.0.0.0:35432:35432
    networks:
      - teiid



networks:
  teiid: