channels:
- currentCSV: local-storage-operator.4.2.11-201912100122
  name: '4.2'
- currentCSV: local-storage-operator.4.2.11-201912100122-s390x
  name: 4.2-s390x
defaultChannel: '4.2'
packageName: local-storage-operator
