apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hadoopflume
  namespace: a6-pro
spec:
  replicas: 1
  selector:
    matchLabels:
      component: hadoopflume
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        service.alauda.io/name: hadoopflume
        component: hadoopflume
    spec:
      containers:
      - env:
        - name: FLUME_AGENT_NAME
          value: "agent"
        - name: JAVA_OPTS
          value: "-Xms100m -Xmx2000m -Dcom.sun.management.jmxremote"
        name: hadoopflume
        image: 11.11.157.191:5000/a6-pro/flume:a6
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "2"
            memory: "4G"
        volumeMounts:
          - mountPath: "/mnt/"
            name: "flume"
            readOnly: false
      volumes:
        - hostPath:
            path: /alauda_data/data/
            type: Directory
          name: "flume"
      nodeSelector:
        ip: "11.11.157.200"
---