apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[{"apiVersion":"charts.helm.k8s.io/v1alpha1","kind":"Citrixcpxistiosidecarinjector","metadata":{"name":"sidecar-inject"},"spec":{"cpxProxy":{"EULA":false,"cpxSidecarMode":true,"image":"quay.io/citrix/citrix-k8s-cpx-ingress","imagePullPolicy":"IfNotPresent","licenseServerPort":27000,"mgmtHttpPort":10080,"mgmtHttpsPort":10443,"tag":"13.0-41.28"},"istioAdaptor":{"ADMIP":null,"image":"quay.io/citrix/citrix-istio-adaptor","imagePullPolicy":"IfNotPresent","netscalerUrl":"http://127.0.0.1","proxyType":"sidecar","secureConnect":true,"tag":"1.0.1"},"istioPilot":{"SAN":"spiffe://cluster.local/ns/istio-system/sa/istio-pilot-service-account","insecureGrpcPort":15010,"name":"istio-pilot","namespace":"istio-system","secureGrpcPort":15011},"sidecarWebHook":{"imagePullPolicy":"IfNotPresent","webhookImage":"gcr.io/istio-release/sidecar_injector","webhookImageVersion":"1.0.0"},"webhook":{"injectionLabelName":"cpx-injection"}}}]'
    capabilities: Basic Install
    categories: Networking
    certified: 'false'
    containerImage: registry.connect.redhat.com/citrix/citrixadcsidecar:1.0.0
    createdAt: '2019-12-04T14:16:17'
    description: In Istio service mesh, a sidecar proxy runs alongside application
      pods and it intercepts and manages incoming and outgoing traffic for applications.
      Citrix ADC CPX can be deployed as the sidecar proxy in application pods. A sidecar
      proxy applies the configured routing policies or rules to the ingress and egress
      traffic from the pod.
    repository: https://github.com/citrix/citrix-istio-adaptor
    support: citrix-cpx-istio-sidecar-injector-operator
  name: citrix-cpx-istio-sidecar-injector-operator.v1.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - description: This is CRD for CPX Istio Sidecar Injector Operator
        displayName: Citrix ADC CPX Istio Sidecar Injector Operator
        kind: Citrixcpxistiosidecarinjector
        name: citrixcpxistiosidecarinjectors.charts.helm.k8s.io
        version: v1alpha1
  description: In Istio service mesh, a sidecar proxy runs alongside application pods
    and it intercepts and manages incoming and outgoing traffic for applications.
    Citrix ADC CPX can be deployed as the sidecar proxy in application pods. A sidecar
    proxy applies the configured routing policies or rules to the ingress and egress
    traffic from the pod.
  displayName: Citrix ADC CPX Istio Sidecar Injector Operator
  icon:
    - base64data: iVBORw0KGgoAAAANSUhEUgAAAZAAAAGQCAYAAACAvzbMAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAH/lJREFUeNrs3f1V28oWxmHb6/4fUkGggkAFQAWYCjAVABUQKjBUAFQAVOBQgaECSAWQCnz1OkyOcWyQrNFoz8zvWUuXc3NOEpBtvdp7PtTt1DSZTNaKLzvFsV0cm2/HWgcAYM3D23FfHD+73e5znT+sWyM4+sWXg+Lo85oAQLSBcl0cV0WYvDYeIEVwDIovp8WxzrkHgCQoPC6K47xKkJQOkCI41Joadv60qwAAaQbJYREit94CpAiP47fwAACk7/YtSF5rBUgRHpfFlwHnEwCyovGR/Y8G2rsfBIdmUo06f2ZVAQDyowpktwiRh6oBMiY8AIAQWRYi3SXhQdsKAOA8vIXI64cBwoA5AGCB2yJA9pcGSBEe68UXta5YSQ4AmHdShMj5sgDRoPkO5wgAsIBaWBuuldWdCQ8Fx4jzAwD4gLY9OZwPEKoPAEAZqkKee2/hsUl4AABKGvytQJi2CwCo4LmoQDZcgLx0mHkFAChvq/fWviI8AABV9DUGwgOhAABVbStAvnMeAAAVbSpAaF8BAKpa6zKADgBYhQJkwmkAABAgQEU/f/6s9N9vbm521tYo2gECBMl4eHjovL6+To/Hx8fprz0/P08P0a/rv2nC+vr69HB2dnamX798+TINnNlfAwgQIDAXAAqEX79+/Q0M9zUWroJxX7e3t/8JIIAAAVaktpKCwQVFbCFRJ1x0KEwULLTLQIAAJcJCbScXFviPq1bUAiNUQIAgW6oiFBgKC32tOoCN95WKAkXBQvsLBAiSdHt727m/v/9bacA/BYirUAgUECCIlga5XWjoK9qpUBQke3t7zP4CAQLbVF3c3d1NA8NNm4UNGi/p9/vT6kRfGT8BAYLWKSxcaOQwQyoVChFVJoQJCBAErzSur68JDcIEIEDwObWkLi4uaE8lbjAY/A0TgADBylRdKDAUHMycyotmcClEjo6OmM0FAgTlKSxctUGLCprBdXBwMK1OAAIEC11dXVFtYCmNjxwfH0/DhKoEBAim4xkaED8/P6faQGmqRhQkrC8BAZJpcJydnU2rDmBVtLdAgGREU3AVHOw/BZ/U0jo9PSVICBAQHMDqQaKZWwoS1pQQICA4gMrcgLvChCAhQEBwACtVJLS2CBBEQlNwT05OCA4QJCBAUA6zqhADbTE/HA6Z/kuAwAKt3dDiP9ZxICYKkMvLSxYkEiBoi6oNtasIDsRKA+1qbTHQToAgEMY5kBKFh9pajI8QIGiQKg2Nc6hdBaRGbS0FicZJQIDAI+2Me3h4SLsKyaOtRYDAE82uUnDQrkJONLiuQXZma9nX4xTYpFbV1tYW4YEsb5x2d3c7+/v7VN1UIKDqAFajVpaqER6zSwUCqg6gElUgqkSoRqhA8MGHRFWHBssBLMbYCAGCOcywAqrRTC1N+QUBkjUtCGRdB1Cd1ovc3NywHQoBkh+tJlfVoa8AVsMqdgIkO7SsAL8UIBobAQGSNFpWQDNoaREgyVK1oYVRtKyA5qilpRBhllY4rANpmEJjY2OD8AAC3ahp01FQgURPz+zQeAeAsDQuogF2NmUkQKLEeAfQLo2LjEYjQoQAiauMZlU5YIPCQyHCc0YIkCjCg8FywF6IsF6EADFNoaHwYH0HYJPWihAiBIg52j2X3UIB+1h0SICYwkwrgBAhQEB4AJnQA6oUIszQIkBaoSm6mqoLIE5M8yVAWqGqQ9UHAEKEAAHhARAinAwChPAAQIgQIIQHAEKEACE8ABAiBAjhAYAQAQFCeAAgRAgQr1gkCBAihAgBQngAWIkej6sQwWI80pbwALCENkrlekAFUoq2ZN/a2uJEAHiHDRgJkE/Dg+d5AFiG54kQIAspNDY2NggPAIQIAVItPHgMLYAyeMY6AfKOniR4e3vLOwFA6RAZj8ed9fX17M9F1rOw9DwPwgNAFepa8AjrzCsQpusCqENPNby5uSFAcvuhmXEFwIcfP350Tk9PCZCcyk+t9Xh+fubdD6A2VSGqRgiQDKjy0OpSAPAh55lZWQ2in52dER4AvFJXQ+OpObbEs6lANNtKMycAoAk5bneSRYBovEPjHgyaA2hSbivVswgQhQcrzQE0LbfxkOTHQDTuQXgACCG38ZCkKxANmGvWFQCEdHx83BkOhwRIzHcCrPcA0JYc1ockGyBskgigTRoPeXp6SvqZ6kmOgSg4CA8AbXLjIVQgkb1oPBwKgBUpt7KSCxBaVwAsSbmVlVQLi9YVAGtSbmUlU4HQugJgWYqtrGQChNYVAMtSbGUl0cLSgkHCA4Bl6o5oZwwqEGPUumLBIIAYaK+snZ0dKhALlOiEB4BYnJycUIFYoOBQ9QEAMdE+WdoviwBpEY+nBRCjVAbUo21hKTgIDwAx0oB6Cq2saCsQBs4BxC72AfUoK5Dz83PCA0D0Yp/WG10FwopzACmJeYV6dBXIxcUF4QEgGTGPhURVgTBtF0CKYp3WG1WAaEfLq6sr3m0AkhLrtN5oWliqPggPAClSW17teSoQqg8AyKIKiaICofoAQBVCBUL1AQCJVCHmKxCqDwBUIVQgVB8AkFAVYroCofoAQBVCBUL1AQAVqpCXlxcCpE4Kf/36lXcSgCxdXl52BoOB6e/RbAsrxkU1AOBLDDv1mqxA2HEXAOzv1GuyArm9vSU8AGTPeifGZAXC0wYB4I/xeNzZ3NykAilDzzknPADAfhVirgLZ39+ftrAAALYXFpqqQFR5EB4A8B+NB1tdD2cqQK6vr3m3AMAcq20sUy0sBs8BYLHRaNTZ2dmhAllErSvCAwAWs9ihMRMgd3d3vEMA4IObbGvr40y0sNj3CgA+Z21/LBMVCDOvAOBz1tpYJiqQra2tzsPDA+8OAPiE1oSsr69TgYgGzgkPACjHUsemx8kAgHhYamO13sKifQUA1VhpY7VagdC+AoDqrHRuepwEAIiLlTZWqy0s2lcAsBoLbazWKhDaVwCwOgsdnF7OPzwAxMrC9k+tBcj9/T3vAABYkZ7e2vbeWFQgABCptq+jvRx/aABIQdudnF6OPzQAUIHU18o0Xp48CAB+jMfjzubmZit/9/9C/4UKDsLDJr0J+/3+u1/TVGsLg3UAFtPns60A6UwCu7y8VMXDYegYDAaTp6enpa/Zy8vL9HVbW1vjfHFwGDt2dnYmbQkeILpY8aLbOBQIRflb+rVTkOjNyrnj4LB1tKXXRrmF9hXh0RmNRpVKX/d75ttcANpvY7UhaIAw/mHHzc3Nyn1TPZfZyhPRALQ3szVogFB92DAYDDo7Ozu1qpfT01NOJEAFkn5K4r2joyMvIUQVAtjQ1sa0vRx+SPxHF31fU/4YCwFs0DT7Nq6vvdR/QLznc7749vY2JxTIuArppfzDodkA0VgIABvaGCLopfzDAQAVCBUIDL4ObG8CECAECG8yqkogAaGn8wYJEN2psoDQBp/Poue5LoC9z3dyAUL1YcvFxUXtP+Pq6oqbAsCYx8dHAgTN0sW/TqmrivLs7IwTCRgT+lobJEB+/frFK2vM/v7+ym82/V6qD4AAoQLJlKqI3d3dSq+N+z3saQbY/VyHnB1JgGT+Ztva2uocHh5+WFHov1PbS48iJjwAqhAnyDPRu90ur2oEeKQtEL/hcNg5Pj4O8nc1/kx07ljjunOhWgTi9vv372B/V+MtLO5cASCckDftjVcgoeclW6X2kA5tp/7ly5elmxqqAtAdhNu9WAchDMDiTXvjAZLrdE/tVKvxhL29venT/8ruXLvoSYFuHEJbh/ha/a2/p85TCX/8+FHp163S+1MTBEL/LO4uMcQNgu/XWjdBeqBYk+fe1/uxqvPz839eD/dZ1uML3EPU3GfRYss36Pc0aVjxxtUgfTaHft6bm5vGzufT09Ok+LBMijdyre9Tf0Ydy/7c2IxGIxM/i76P4XA4KS7Mk+KC5fU92cRrre/XyvWh7s/n6PzP/9lFcExeXl6m/348Hk9/bh3u1/RZ9/16+Tjc99e0xj8lm5ub2QSHrw9VWZeXlysHCQFiK0Dm6WLlK0yaeK31vvNxkdINUZ2fUdcXXzdm89+Hzr97j8x/zvTfHh8f/32trIVIqGtR45+S1INDbxxdyNuiD7EuEARIWgFS9/UN8Vq7C2gTd/6hL5TzN7oKDFdhuL9n9tCv6/e4ANM1gAAhQCpXHaFKxTJ3UFWqPQIkjgCZrUhWreabeq3bbmX5CrBFAa1A0GfbVRYuJPTfKvD07/SZmz2/ddvKltqWJgLkow9n7IevN69vZe9WCZC4AsRVI6uESJMB0lYry9ffq2BeNoYwWxnNh5w7p64LIbom5BYgvQ4qK+5Epqs9LTo9Pe0U5TXPK090Zl8ReF6fa+9jJpWPnZk1u0nv3SqfQR/vcW3js+g867i7u3v36wcHB9PZXjo0u9LNMNWsLc2qs/SZCzWVt5fCDxE6PHxMYWySphzqQkOIpBki1m4QNPXVx/Rybb9RJhz139WZluwo+BZNeV12bvW5V8jp0H+jXamtCjWVt9EASW0RoaoO6+Hh6INY5Y4O8dDdeqi9jqrcyfu4YdQNms9K5aML7LK1I66ymA8z7UStff30exUgs2vcLFWFIdHCKknBYe1DG6K1AJvcXbAVCo9F7aBVbnw+WhSom7imWlezVFEdHR0t/b36HlzY6dqg/2/pEc9JtLBSoTf1Z3dG1vi6I4Rd1m5odAH1cRFVOC66o1drdn636FWcnJx82uLRY5+XVXr6vWrb6XtxbS2NgVhalR7se2lyhD6VVeiaqRGTMvPqmYUV3yysRTOXOi3PwuosWBfVxOwoX39ulZmhbn3XspmNmhGn73PV2XFNH8zCMkDldEz9TVpX+dAdstubKfVWlo9ZV1W/N/23qjRUYRRh/XcMVN+XJjIU4TH9nqo+2TMl/+Nj+PEHdFkflNYVPqJNAq+vr99dEHWx0YZ8PmYQzf651jYsda2suu0mffZ0Hhc96GwVurGqeq7U7tJ0Xk3hdWMdrkWkf6fvz+rnTd9X0+NkBMgnvdimXgC3u67759k7yu/fv//d+r3qB7ftB3jpbmzVC2GdtTVl+trLPmRN+PXr17vXYvaf9brqZ/VxUdR5szR4O3sjs8p7eJYbqPZRZen8q5pY9ffq8FFZhaTPg8+blYWa7I9ZWtpf9XB74fjuWVfZIE99VbelQplVylVW8obsi3dKbgtjbbyt6R0BfOyhVmYPprZe67qvqc8V/DFfizqG98NqdAwk5meB+F7voTvkjY2NSiWv7iB016Pf99ndE62r+Og9Ufc1szYG4uuu36dVWlcoh0H0JdTz9NWH3NraqvVB0p+hi43aQ4suOL6mTyJ8jzr1163ti7fOr4UQI0AyUrd3O3uB8DlDQ3d08yHia9YL2qGxktRDsq33J58NAqQVPgY3RXvl+J7epz9vNkRoXcWt7UkPoX7GNqoAPhsESCs01bIufWCauji4KYS0ruLnY21DDJZtXNgUPhsESGvqTn3Th7rpxXwajLe8GyjKqbtINZYNS0O2k2hdESDRfqDdxZ3SGSGq3ZhmF6kCCbFLAq0rAqQ1PgbPZ1cgAx9VunWr3djGULQNSJOtLN280boiQKKtQHTnk+u+OKj2PtN+SnWrjxjXNzTVXtK50NggCJBoER74iGb4aXsOtxFfjpVuU60sWlfhsReWZ25/K+RNC1Fnxzd875yrC2XMC+TUytJmib72mrOwDxwBgulGhkBdTW+1rgcexXy3rUrM50alGkvS+WbLkrBoYc2x9JhQYBH3RLyYP2O+n/DZxJ8JAmSlDydglVvjEHP14ePhUMuqEGuP+SVAaojpSX7O79+/a/3+L1++8K5CY+ER+9PvfD3XfBk9w8fyDsUESMWyMjcxhibs0wCxdnWOOTxCtJloZSUUILHe5dUtowFfNCislpUqj9gHiJtqXS36DM4+Tz1XIW5mCZA5Pu7wmizRkQdNS3UPE9Pq6tg13bqap1ZW7t2AEGFNgDQQIJrfDqxKi+y0UWYKweEuZG20lWhlNa/RAImxnaMWVt1WgY89jj6jgULfj92FDandPYdqXc3TOaSVRQUSnI8VrcPhsLEPjf5c7aOkv4NB+zSlcvccunWVehhXCU8CpCU+tiPRC6gLfBPhMRqNpn++aw2w+DG9m5AU7p6tzIjKsZUV6prQaIDEui2Ir+2g1WLy+eadDY+mgwr1b0LqjmHo7jnmWX0+bm58LJiklRVpgMR6Z6w3rc8Q0UW/7uImXUienp4Wlqb6OxgPsUdbi9e9AMZaYfpqXWkmmo9tW3JrZdHCapnPrbJ18df23boLqnox0O9VAOn46PeqCmEFrr0bkbrblus11cUvJr5aV+655jqHPtbA5NTKCnbTMWmY/opYj+KOv5FzcnNzMykqhkkRDv/8ncUFY1LcuU2KQKj89xchVfpnK8LM1Ouqc1HHonNZ96hD59fn+6jOzxf6tdb7u66Xl5fpZ8HX+2PR65LyoetHCATIB4cu8rHRG4cAsRUgPi5+CqHirtJ8gPj6zBwfHzd2Udzc3Ew+QEajUZDrTeMtrJj7jhoEje0hNdqNlJXwtug9VHdMTa0s6y0YfY8+JnTofC0a91Ary8egOgsMIxoDiX2KaYzPWNYHhPEQe++juhe/ttdUlHnf+Zh1teyZ6R/9u6o3tanPygo1e6/xAIn9QtbU85ubDm0tNIQdGgTWUwQtXKSbqnx9XLQ+GzB3A+t1sVcWARKM7lZia2Ux993m+6jubCKL25X7milW9kmLvh6olWorK+TaocYDJJVnjGtzu9iexfDt2zeu2sb4aImqjWXpyXu+qqKy7SlaWRlVIKlssxHbo0Q1AcDHhwx+qf3io5q18uQ9n62rKjdoPs9jaq2spCqQlB6wpDe4HuxjPUQID9t8vDYWWlk+W1erVAK0strvPARZiZ7SZn96s1t+tKhaJISHbRoH8TExQzdnbbayQreumjqPqbWyQlamQQIktRJRb1xVIr72y/L5PfnYNwjN0+vkY3uOtlowbbWuFp1HWlntXW8JkBWpdNbAuo/5/T4uRqqKYpspljMf+2S56j50C8ZX60oB6uOGh1bW+/dDyI5PkABJeTaQu3i38fhRBYb+bgshhup87XQQugXjs3Xl431LK6u9m3UqEA/0BtaHYWNjI0iQ6KKjdpWO2KYW4z1fOx2EasH4al35aj3N/nk+PguxP4MlyQBJaSZW2SDRhcHnxd2V+/qzFRy0q9JQdvFc2cqgST5bV03s7uBr8kjMrazQ6+66b7ttNk4XPh+DhrHRh053Bdvb29Ov+v+fzZJQWa8Li87X4+PjdLA+x3MHoBo9dyhkFRIsQDTgbGnWkhWqzhQOBASAugJdzv8K9kRCNi5bTK0owgNAjNfY/4X6i9TCAWDrgjM7m0ptU2bzxauVseaQT8vrZPAoSQ4Oy4ceE6sn++mRscsei6ynCnKu4jsuLy+DPwE1aIDk8ChJDg6rhx4Tuyw4FgUJn9e4Dr1mSQfIouccc3Bw2Lw7VdgQInEca2trkzYEG0SXVJ4NAsREi/8Gg0Hl36fxkdFolNRmqIx/+NXL4YcEclV38Z/CYzgcciKNa2uSUi/0mzmFR9wCsTg6OqpdQah64XNrW1vLJHqh/0KqECCcVVpXTf458E83CFm0sNostYAc70p9jV/wubWrzZtyKhAg4TtTi38W0rkpDx4gjIMA8eEzSwViIkCk3+/zqgMR4bkzdoO9zX0GWwkQ+qlAXBd9Nvyk+qACATLinivjw/39PSfUoL29vfwChBABwri4uPASRCEe1QwqkGiSE8iBLvx1H3/s67nt8H8T3vbsuNYChOm8QBh6Vviqz/lQAFF92GRiLHnSInb65OAIc+iz9vT0VOnzqR18OXd2j6qvZ/Tbuc/Tg214I3BwhNvyu8y27row9ft9zpnxGwILupPQT2GfoamBGxsb1KJAQFo7oP65WiCzPXR9Hu/u7jq3t7ecJOO0Q7K26W9bqwEiW1tbLFICgAqKKtHE7gC9tr+Bg4MD3g0AUJJWnlvZWqb1AGE9CADEedPdegtLdnd3a89VB4AcWGlfmahArCUqAFiljo2lnZF7Vk4KAOBj1nbwMNHCEq2WZcUrACymKdcvLy+mvqeelW+ENhYALGexU2OmAhEtKuS5AwDwr/F43OrDo0xXIHJ0dMS7BADmKDishYe5CkQ7hn79+pV3CwDMuLy87AwGA3Pfl6kKRINEFk8SALR5XbQ6U7Vn7RtiMB0A/mPhwVHLmGphOWywCAB/WFp5br4CEQbTAeDPk1uthofZCkQ0mL7qYzgBIAWj0cj04797Vr8xCw9LAYC2qPKwHB6mKxBVH1pYSBUCIEdWp+5GUYFYnroGAE1XHzEsaehZ/uZOT095JwHITiwTicy2sBx26QWQE3VfNHXX6tqPaCoQqhAAudEEohjCI4oKhCoEANUHFQhVCAAkUn1EU4FQhQCg+qACoQoBgASqj6gqEKoQAKnSug9VH7GJKkBYnQ4gRTGsOl+kF9M3q/KOPbIApFZ9xPogvagqEKoQAKmxvuNuMhWIq0KGwyHvOgDRU3DEGh5RViAOTy0EELvxeNzZ3NyM9vvvxfqNU4UAiJnGc2MOj6grENnf3+/c3t7yTgQQlRgXDSZVgbgqJPYXAEB+tDA6hWtX1AGi6W9M6wUQE7WtUrluRd3CchhQBxCL2AfOk6lAHAbUAcQghYHz5CoQOTk56Zyfn/MOBWCSWu6qPlIat00mQFihDsCym5ubTr/fT+pn6qXygyjVtSEZAFij4EgtPJKqQBzWhgCwdnObwpqPLAKEVhYAS1JsXTm91H4gWlkArEi1dZVsBeIwKwtAm1KcdZVNgKiFpQWGz8/PvJMBBBfzcz7K6qX6gyn11XsEgNB+/PiRfHgkXYE4Z2dn0xcTAELQSnO1rnKQfIDI7u5u5+fPn7yzATRKnQ+Fh8Y/CJBEMLUXQAgpT9ldpJfDD8l4CICmaaPEnMIjmwrEYTwEQBNyGvfINkCErU4A+JTbuEfWAaJxEA2q8wAqAD7ksN5jmV5uP7Db6oRnqQOoSw+zyzU8sqxAHLWx1M4CgFUMBoPs993LNkBEe2VpzywAqEKD5mpd5d7JyDpA5PDwsHN1dcUnAkApOWySSIBUoE0XGVQH8BmFhioPVSDIcBB9Ed4QAMrQmAfXCiqQf6gC0fRetjsBsCw8NHAOKpB/MCgGYBntYEF4UIF8Srv2qhIBAGG6LhVIaVoUxJsFAOFBBbIyTe3VFF8A+d5Mqq0NAoQQAVAaY6IEiBdaqa4V6wAIDxAglbFaHSA8QIAQIgAIDwKEEAFAeBAghAgAwoMAyQGzswDCAywkXAmLi4D49ft9woMKhEoEADeBBEiE9GhchQi7+AKEBwGCytgKHojDcDjsHB8fcyIIEHshokqEJxsCNvE8DwLENFUgqkQIEcAODZLf3NxMN0eEX8zC8vxG1awO7nIAG9bX16efScKDCiQqZ2dn06eYAWgHazwIkKhpmq9282VwHQiLmVYESBI0HrK/v995fn7mZAABMFhOgCRFFYhCRM9bB9AMNwap1hXCYBA94BubMRGgGRokf3p6IjyoQNKmKkTVCOMigB9aGKgFgiBAskBLC/BT2Wu8Q5sioh20sFp649PSAlbnWlaEBxVI1lSFaAsUZmkB5ejG6/T0lBNBgEDU0lKIaGdfAItpgFwtKwbK7aCFZYDbq0cHq2aBf2mgnCm6VCCgGgFK015WqjrYy4oKBFQjQKWqYzweEx5UIKAaAcpRm0rrOggOAgQeMFMLuWCGFQGChqqRi4sL1o4gSao2NNahMQ8QIGiIqhBVI6xiRwoUGGpXsSCQAEFAGhfRs0ZoayFGmiCiQfKjoyMmixAgaIuefHh+fs7mjIiGntWhcQ7aVQQIDFB4uCABrNI4h4KD2VUECAxSO0tBokfpAlawGJAAQWRBwkA7LASHKg4eL5suVqIn+sHVvkE6uOtDWxWHtlsnPKhAEDlVImptUZGAigMECFbCGAmaoK1HNB2X4CBAkEmQaFW7goTpv1gVs6pAgGRM4aEQUZiwIBFlsY4DBAje0cp2BQnjJFhEYeHaVKwcBwGChWhvYZb2qDo4OGCvKhAgqEYhcnd3x/NIMq02FBq0qUCAoHZV4lpcjJWkSW0pBYaCg+eOgwBBIx4eHjrX19fTQCFM0giNvb09WlQgQECYgNAAAYIIw8SNl+ifYYfGMbRWg9AAAQLzVI1oOrACRV+ZzRWeCwx9ZUwDBAiir04UJqwzaYZCQmGxvb09/cpaDRAgSJJC5P7+fhosVCirVxgKDQIDBAiy5lpej4+Pf0MF76sLHd+/f/9baQAECLCEgkTBolBRoOifU5/ppSrChcW3b98ICxAggO9gUctLLTB9df8/lplfLiTcVwWFZkm5XwMIEKAFs0Gir79//34XOo7vFtn8xX+2atAYhSgk2BYEBAiQqI/aZK5iAECAAAA8BMiLbrA4FQCAKnrFwb4TAICVAoRVXACAql4VII+cBwBARQ8KEB43BwCo6r6r/2UgHQBQ0Vbv7R+oQgAAZT13u90HFyAXnA8AQEnX+p+u+3+TyWRUfNnhvAAAPrFRVCDPvZlfOOOcAAA+caXweFeBUIUAAD7x+lZ9vC4KkPXiy7jDjCwAwL9OivA4d/+nO/9vixA5Lr4MOU8AgBm3RXjsz/5Cd9F/VYTIZfFlwPkCAHT+7Jm461pXHwbIW4iolcUDEAAgb69v4fHPxrsfBYjGQUaECAAQHov+Zfez3007CwCypNDYd1N2VwqQtxBhYB0A8qHtrQ7nxzxWCpC3ENl8C5Edzi0AJOn1LThK7Y/YrfqnF0EyKL6cFsc65xoAkgkO7Yl4/lnVUStAZoKkX3w5KI4+5x4AovTwFhy3VYKjdoDMBIlma+0Ux3bnz4wtHaxkBwCbgaHjvjh+fjRAXsb/BRgAFMSa3R8dbEUAAAAASUVORK5CYII=
      mediatype: image/png
  install:
    spec:
      clusterPermissions:
        - rules:
            - apiGroups:
                - ''
              resources:
                - namespaces
              verbs:
                - get
            - apiGroups:
                - ''
              resources:
                - configmaps
                - secrets
              verbs:
                - '*'
            - apiGroups:
                - admissionregistration.k8s.io
              resources:
                - mutatingwebhookconfigurations
              verbs:
                - '*'
            - apiGroups:
                - ''
              resources:
                - configmaps
                - serviceaccounts
                - services
              verbs:
                - '*'
            - apiGroups:
                - extensions
              resources:
                - networkpolicies
              verbs:
                - '*'
            - apiGroups:
                - monitoring.coreos.com
              resources:
                - servicemonitors
              verbs:
                - get
                - create
            - apiGroups:
                - apps
              resourceNames:
                - citrix-cpx-istio-sidecar-injector-operator
              resources:
                - deployments/finalizers
              verbs:
                - update
            - apiGroups:
                - ''
              resources:
                - pods
              verbs:
                - get
            - apiGroups:
                - apps
              resources:
                - replicasets
              verbs:
                - get
            - apiGroups:
                - charts.helm.k8s.io
              resources:
                - '*'
              verbs:
                - '*'
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - clusterroles
                - clusterrolebindings
              verbs:
                - '*'
            - apiGroups:
                - extensions
              resources:
                - deployments
              verbs:
                - '*'
            - apiGroups:
                - apps
              resources:
                - deployments
              verbs:
                - '*'
          serviceAccountName: citrix-cpx-istio-sidecar-injector-operator
      deployments:
        - name: citrix-cpx-istio-sidecar-injector-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                name: citrix-cpx-istio-sidecar-injector-operator
            strategy: {}
            template:
              metadata:
                labels:
                  name: citrix-cpx-istio-sidecar-injector-operator
              spec:
                containers:
                  - env:
                      - name: WATCH_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.annotations['olm.targetNamespaces']
                      - name: POD_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                      - name: OPERATOR_NAME
                        value: citrix-cpx-istio-sidecar-injector-operator
                    image: registry.connect.redhat.com/citrix/citrixadcsidecar:1.0.0
                    imagePullPolicy: Always
                    name: citrix-cpx-istio-sidecar-injector-operator
                    resources: {}
                serviceAccountName: citrix-cpx-istio-sidecar-injector-operator
    strategy: deployment
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: true
      type: AllNamespaces
  keywords:
    - istio sidecar injector
  links:
    - name: citrix-cpx-istio-sidecar-injector-operator
      url: https://github.com/citrix/citrix-istio-adaptor
  maintainers:
    - email: ajeeta.shakeet@citrix.com
      name: Citrix
  maturity: alpha
  provider:
    name: Citrix
  version: 1.0.0
