apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: citrixcpxistiosidecarinjectors.charts.helm.k8s.io
spec:
  group: charts.helm.k8s.io
  names:
    kind: Citrixcpxistiosidecarinjector
    listKind: CitrixcpxistiosidecarinjectorList
    plural: citrixcpxistiosidecarinjectors
    singular: citrixcpxistiosidecarinjector
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
