apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: "[\n  {\n    \"apiVersion\": \"charts.helm.k8s.io/v1alpha1\",\n\
      \    \"kind\": \"Cortex5\",\n    \"metadata\": {\n      \"name\": \"no-infra-cortex5\"\
      \n    },\n    \"spec\": {\n      \"accounts\": {\n        \"tag\": \"5.0.492-g05eb988-ubi7\"\
      \n      },\n      \"actions\": {\n        \"tag\": \"5.0.577-g2081776-ubi7\"\
      \n      },\n      \"adminui\": {\n        \"tag\": \"5.0.5-g564032f-ubi7\"\n\
      \      },\n      \"agents\": {\n        \"tag\": \"5.0.399-g92ae742-ubi7\"\n\
      \      },\n      \"catalog\": {\n        \"tag\": \"5.0.296-ge185713-ubi7\"\n\
      \      },\n      \"connections\": {\n        \"tag\": \"5.0.288-g5eba827-ubi7\"\
      \n      },\n      \"connectiontypeloader\": {\n        \"tag\": \"5.0.32-gc4e0c74-ubi7\"\
      \n      },\n      \"cortex\": {\n        \"imageRegistry\": \"610527985415.dkr.ecr.us-west-2.amazonaws.com\"\
      ,\n        \"managedContent\": {\n          \"S3_BUCKET\": \"colt-clean-test-content\"\
      ,\n          \"S3_ENDPOINT\": \"https://s3.amazonaws.com\",\n          \"S3_REGION\"\
      : \"us-east-1\",\n          \"accesskey\": \"{{.AWS_ACCESS_KEY_ID}}\",\n   \
      \       \"secretkey\": \"{{.AWS_SECRET_ACCESS_KEY}}\"\n        },\n        \"\
      mongodb\": {\n          \"graphUri\": \"mongodb://$(MONGODB_USERNAME):$(MONGODB_PASSWORD)@performance-testing-etur0.mongodb.net/cortex-graph?authSource=admin\\\
      u0026replicaSet=rs0\",\n          \"metricsUri\": \"mongodb://$(MONGODB_USERNAME):$(MONGODB_PASSWORD)@performance-testing-etur0.mongodb.net/cortex-metrics?authSource=admin\\\
      u0026replicaSet=rs0\",\n          \"mongoUri\": \"mongodb://$(MONGODB_USERNAME):$(MONGODB_PASSWORD)@performance-testing-etur0.mongodb.net/cortex-admin?authSource=admin\\\
      u0026replicaSet=rs0\",\n          \"password\": \"L7HlijT6aCJi8tE2\",\n    \
      \      \"username\": \"cortex\"\n        },\n        \"postgresql\": {\n   \
      \       \"password\": \"\"\n        },\n        \"redis\": {\n          \"env\"\
      : {\n            \"REDIS_TYPE\": \"node\"\n          },\n          \"password\"\
      : \"something\",\n          \"redisUri\": \"redis://:$(REDIS_PASSWORD)@cortex-redis-master-0.cortex-redis-headless.cortex.svc.cluster.local:6379\"\
      \n        }\n      },\n      \"datasets\": {\n        \"tag\": \"5.0.86-gb3a1b0b-ubi7\"\
      \n      },\n      \"deployModel\": {\n        \"type\": \"openshift\"\n    \
      \  },\n      \"docker-registry\": {\n        \"enabled\": false\n      },\n\
      \      \"docs\": {\n        \"tag\": \"5.1.52-g45a7f49-ubi7\"\n      },\n  \
      \    \"elasticsearch\": {\n        \"enabled\": false\n      },\n      \"filebeat\"\
      : {\n        \"enabled\": false\n      },\n      \"graph\": {\n        \"tag\"\
      : \"5.0.72-gc8917a5-ubi7\"\n      },\n      \"kibana\": {\n        \"enabled\"\
      : false\n      },\n      \"kong\": {\n        \"tag\": \"5.0.88-gea2a5d8-ubi7\"\
      \n      },\n      \"logWriteAccess\": {\n        \"enabled\": false\n      },\n\
      \      \"logs\": {\n        \"env\": {\n          \"ELASTICSEARCH_HOST\": \"\
      ecd7bc77797941978322593d049dfd8d.us-east-1.aws.found.io:9243\",\n          \"\
      ELASTICSEARCH_PASS\": \"U48HPRNgPdR8TQ368E02lFuE\",\n          \"ELASTICSEARCH_PROTO\"\
      : \"https\",\n          \"ELASTICSEARCH_USER\": \"elastic\"\n        },\n  \
      \      \"tag\": \"5.0.65-gc7ab2b2-ubi7\"\n      },\n      \"metrics\": {\n \
      \       \"tag\": \"5.0.77-g02efa69-ubi7\"\n      },\n      \"minio\": {\n  \
      \      \"enabled\": false\n      },\n      \"models\": {\n        \"tag\": \"\
      5.0.52-g880e03e-ubi7\"\n      },\n      \"mongodb-replicaset\": {\n        \"\
      enabled\": false\n      },\n      \"nginx-ingress\": {\n        \"enabled\"\
      : false\n      },\n      \"postgresql\": {\n        \"enabled\": false\n   \
      \   },\n      \"processorgateway\": {\n        \"tag\": \"5.0.175-g36c3ad1-ubi7\"\
      \n      },\n      \"rabbitmq\": {\n        \"enabled\": false,\n        \"persistence\"\
      : {\n          \"enabled\": false\n        },\n        \"volumePermissions\"\
      : {\n          \"enabled\": false\n        }\n      },\n      \"redis\": {\n\
      \        \"enabled\": false\n      },\n      \"sessions\": {\n        \"tag\"\
      : \"5.0.35-gf1bf851-ubi7\"\n      }\n    }\n  }\n]"
    capabilities: Basic Install
  name: cortex-operator.v0.1.2
  namespace: cortex
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - description: A Cortex5 app cluster.
        displayName: Cortex5
        kind: Cortex5
        name: cortex5s.charts.helm.k8s.io
        resources:
          - kind: ServiceAccount
            name: ''
            version: v1
          - kind: Role
            name: ''
            version: v1
          - kind: RoleBinding
            name: ''
            version: v1
          - kind: Deployment
            name: ''
            version: v1
          - kind: ReplicaSet
            name: ''
            version: v1
          - kind: Pods
            name: ''
            version: v1
        specDescriptors:
          - description: Internal deployment model
            displayName: Deploy Model
            path: deployModel
          - description: Redis disabled in operator
            displayName: Redis
            path: redis
          - description: Elasticsearch disabled in operator
            displayName: Elasticsearch
            path: elasticsearch
          - description: Cortex Model Service
            displayName: Cortex Model Service
            path: models
          - description: Cortex Dataset Service
            displayName: Cortex Dataset Service
            path: datasets
          - description: Docker Registry disabled in operator
            displayName: Docker Registry
            path: docker-registry
          - description: Minio disabled in operator
            displayName: Minio
            path: minio
          - description: PostgreSQL disabled in operator
            displayName: PostgreSQL
            path: postgresql
          - description: Cortex Metric Service
            displayName: Cortex Metric Service
            path: metrics
          - description: Filebeat disabled in operator
            displayName: Filebeat
            path: filebeat
          - description: Cortex CData Connection Type Loader
            displayName: Connection Type Loader
            path: connectiontypeloader
          - description: Cortex Catalog Service
            displayName: Cortex Catalog Service
            path: catalog
          - description: RabbitMQ disabled in operator
            displayName: RabbitMQ
            path: rabbitmq
          - description: Cortex Admin-UI
            displayName: Cortex Admin-UI
            path: adminui
          - description: Cortex Agent Service
            displayName: Cortex Agent Service
            path: agents
          - description: Cortex Docs Service
            displayName: Cortex Docs Service
            path: docs
          - description: MongoDB Replicaset disabled in operator
            displayName: MongoDB Replicaset
            path: mongodb-replicaset
          - description: Cortex Session Service
            displayName: Cortex Session Service
            path: sessions
          - description: Cortex Action Service
            displayName: Cortex Action Service
            path: actions
          - description: Base Cortex5 properties
            displayName: Cortex5
            path: cortex
          - description: Kibana disabled in operator
            displayName: Kibana
            path: kibana
          - description: Nginx-Ingress disabled in operator
            displayName: Nginx-Ingress disabled in operator
            path: nginx-ingress
          - description: Cortex Log Service
            displayName: Cortex Log Service
            path: logs
          - description: Cortex Processor Gateway Service
            displayName: Cortex Processor Gateway Service
            path: processorgateway
          - description: Cortex Account Service
            displayName: Cortex Account Service
            path: accounts
          - description: Cortex Connection Service
            displayName: Cortex Connection Service
            path: connections
          - description: Cortex Graph Service
            displayName: Cortex Graph Service
            path: graph
          - description: Cortex Kong Service
            displayName: Cortex Kong Service
            path: kong
          - description: Log Write Access disabled in operator
            displayName: Log Write Access
            path: logWriteAccess
        statusDescriptors:
          - description: conditions
            displayName: conditions
            path: conditions
          - description: deployedRelease
            displayName: deployedRelease
            path: deployedRelease
        version: v1alpha1
  description: Placeholder description
  displayName: Cortex Operator
  install:
    spec:
      deployments:
        - name: cortex-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                name: cortex-operator
            strategy: {}
            template:
              metadata:
                labels:
                  name: cortex-operator
              spec:
                containers:
                  - env:
                      - name: WATCH_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.annotations['olm.targetNamespaces']
                      - name: POD_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                      - name: OPERATOR_NAME
                        value: cortex-operator
                    image: registry.connect.redhat.com/c12e/cortex5-fabric-operator:0.1.2
                    imagePullPolicy: Always
                    name: cortex-operator
                    resources: {}
                serviceAccountName: cortex-operator
      permissions:
        - rules:
            - apiGroups:
                - ''
              resources:
                - pods
                - services
                - services/finalizers
                - endpoints
                - persistentvolumeclaims
                - events
                - configmaps
                - secrets
              verbs:
                - '*'
            - apiGroups:
                - apps
              resources:
                - deployments
                - daemonsets
                - replicasets
                - statefulsets
              verbs:
                - '*'
            - apiGroups:
                - ''
              resources:
                - namespaces
              verbs:
                - get
            - apiGroups:
                - ''
              resources:
                - configmaps
                - secrets
              verbs:
                - '*'
            - apiGroups:
                - monitoring.coreos.com
              resources:
                - servicemonitors
              verbs:
                - get
                - create
            - apiGroups:
                - apps
              resourceNames:
                - cortex-operator
              resources:
                - deployments/finalizers
              verbs:
                - update
            - apiGroups:
                - ''
              resources:
                - pods
              verbs:
                - get
            - apiGroups:
                - apps
              resources:
                - replicasets
                - deployments
              verbs:
                - get
            - apiGroups:
                - charts.helm.k8s.io
              resources:
                - '*'
              verbs:
                - '*'
          serviceAccountName: cortex-operator
    strategy: deployment
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: false
      type: AllNamespaces
  keywords:
    - CognitiveScale
    - Cortex5
    - Fabric
  maintainers:
    - email: mcriscolo@cognitivescale.com
      name: Michael Criscolo
  maturity: alpha
  provider:
    name: CognitiveScale
  version: 0.1.2
