apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cortex5s.charts.helm.k8s.io
spec:
  group: charts.helm.k8s.io
  names:
    kind: Cortex5
    listKind: Cortex5List
    plural: cortex5s
    singular: cortex5
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            accounts:
              tag:
                type: string
            actions:
              tag:
                type: string
            adminui:
              tag:
                type: string
            agents:
              tag:
                type: string
            catalog:
              tag:
                type: string
            connections:
              tag:
                type: string
            connectiontypeloader:
              tag:
                type: string
            cortex:
              type: object
            datasets:
              tag:
                type: string
            deployModel:
              type: object
            docker-registry:
              enabled:
                type: boolean
            docs:
              tag:
                type: string
            elasticsearch:
              enabled:
                type: boolean
            filebeat:
              enabled:
                type: boolean
            graph:
              tag:
                type: string
            kibana:
              enabled:
                type: boolean
            kong:
              tag:
                type: string
            logWriteAccess:
              enabled:
                type: boolean
            logs:
              tag:
                type: string
            metrics:
              tag:
                type: string
            minio:
              enabled:
                type: boolean
            models:
              tag:
                type: string
            mongodb-replicaset:
              enabled:
                type: boolean
            nginx-ingress:
              enabled:
                type: boolean
            postgresql:
              enabled:
                type: boolean
            processorgateway:
              tag:
                type: string
            rabbitmq:
              enabled:
                type: boolean
            redis:
              enabled:
                type: boolean
            sessions:
              tag:
                type: string
        status:
          properties:
            conditions:
              type: array
            deployedRelease:
              type: object
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
