apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: storagenodes.core.libopenstorage.org
spec:
  additionalPrinterColumns:
    - JSONPath: .status.nodeUid
      description: The corresponding Kubernetes node name for the storage node
      name: ID
      type: string
    - JSONPath: .status.phase
      description: The status of the storage node
      name: Status
      type: string
    - JSONPath: .spec.version
      description: The version of the storage node
      name: Version
      type: string
    - JSONPath: .metadata.creationTimestamp
      description: The age of the storage cluster
      name: Age
      type: date
  group: core.libopenstorage.org
  names:
    kind: StorageNode
    listKind: StorageNodeList
    plural: storagenodes
    shortNames:
      - sn
    singular: storagenode
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          description: The desired behavior of the storage node. Currently changing
            the spec does not affect the actual storage node in the cluster. Eventually
            spec in StorageNode will override the spec from StorageCluster so that
            configuration can be overridden at node level.
          properties:
            cloudStorage:
              description: Details of storage on the node for cloud environments.
              properties:
                driveConfigs:
                  description: List of cloud drive configs for the storage node.
                  items:
                    properties:
                      iops:
                        description: IOPS required from the cloud drive.
                        format: int32
                        minimum: 0
                        type: integer
                      options:
                        description: Additional options for the cloud drive.
                        type: object
                      sizeInGiB:
                        description: Size of cloud drive in GiB.
                        format: int64
                        minimum: 0
                        type: integer
                      type:
                        description: Type of cloud drive.
                        type: string
                    type: object
                  type: array
              type: object
            version:
              description: Version of the storage driver on the node.
              type: string
          type: object
        status:
          description: Most recently observed status of the storage node. The data
            may not be up to date.
          properties:
            conditions:
              description: Contains details for the current condition of this storage
                node.
              items:
                properties:
                  reason:
                    description: Reason is the human readable message indicating details
                      about the current state of the cluster.
                    type: string
                  status:
                    description: Status of the condition.
                    type: string
                  type:
                    description: Type of the condition.
                    type: string
                type: object
              type: array
            geography:
              description: Contains topology information for the storage node.
              properties:
                rack:
                  description: Rack on which the storage node is placed.
                  type: string
                region:
                  description: Region in which the storage node is placed.
                  type: string
                zone:
                  description: Zone in which the storage node is placed.
                  type: string
              type: object
            network:
              properties:
                dataIP:
                  description: IP address used by the storage driver for data traffic.
                  type: string
                mgmtIP:
                  description: IP address used by the storage driver for management
                    traffic.
                  type: string
              type: object
            nodeUid:
              description: Unique ID of the storage node.
              type: string
            phase:
              description: Phase of the StorageNode is a simple, high-level summary
                of where the StorageNode is in its lifecycle. The condition array
                contains more detailed information about the state of the node.
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
