apiVersion: operator.openshift.io/v1
kind: Network
metadata:
  name: cluster
spec:
  additionalNetworks: 
  - name: slbl7-001-macvlan
    namespace: zxcdn
    type: SimpleMacvlan
    simpleMacvlanConfig:
      # master: enp3s0f0
      # mode: bridge
      ipamConfig:
        type: static
        staticIPAMConfig:
          addresses:
          - address: 39.137.101.50/25
          routes:
          - destination: 0.0.0.0/0
            gateway: 39.137.101.126
  - name: ottcache-001-macvlan
    namespace: zxcdn
    type: SimpleMacvlan
    simpleMacvlanConfig:
      # master: enp3s0f0
      # mode: bridge
      ipamConfig:
        type: static
        staticIPAMConfig:
          addresses:
          - address: 39.137.101.52/25
          routes:
          - destination: 0.0.0.0/0
            gateway: 39.137.101.126
  - name: ottcache-002-macvlan
    namespace: zxcdn
    type: SimpleMacvlan
    simpleMacvlanConfig:
      # master: enp3s0f0
      # mode: bridge
      ipamConfig:
        type: static
        staticIPAMConfig:
          addresses:
          - address: 39.137.101.54/25
          routes:
          - destination: 0.0.0.0/0
            gateway: 39.137.101.126
  - name: ottcache-003-macvlan
    namespace: zxcdn
    type: SimpleMacvlan
    simpleMacvlanConfig:
      ipamConfig:
        type: static
        staticIPAMConfig:
          addresses:
          - address: 39.137.101.51/25
          routes:
          - destination: 0.0.0.0/0
            gateway: 39.137.101.126            
  - name: slb-001-macvlan
    namespace: zxcdn
    type: SimpleMacvlan
    simpleMacvlanConfig:
      ipamConfig:
        type: static
        staticIPAMConfig:
          addresses:
          - address: 39.134.201.75/27
          routes:
          - destination: 0.0.0.0/0
            gateway: 39.134.201.94
  - name: slb-002-macvlan
    namespace: zxcdn
    type: SimpleMacvlan
    simpleMacvlanConfig:
      ipamConfig:
        type: static
        staticIPAMConfig:
          addresses:
          - address: 39.134.201.76/27
          routes:
          - destination: 0.0.0.0/0
            gateway: 39.134.201.94
  - name: webcache-001-macvlan
    namespace: zxcdn
    type: SimpleMacvlan
    simpleMacvlanConfig:
      ipamConfig:
        type: static
        staticIPAMConfig:
          addresses:
          - address: 39.134.201.77/27
          routes:
          - destination: 0.0.0.0/0
            gateway: 39.134.201.94
  - name: webcache-002-macvlan
    namespace: zxcdn
    type: SimpleMacvlan
    simpleMacvlanConfig:
      ipamConfig:
        type: static
        staticIPAMConfig:
          addresses:
          - address: 39.134.201.78/27
          routes:
          - destination: 0.0.0.0/0
            gateway: 39.134.201.94
  
