version: '3'
services:

  hadoopmysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "hive"
    restart: unless-stopped
    networks:
      - esnet
    volumes:
      - hadoopmysql:/var/lib/mysql

  namenode:
    image: cdh:wzh
    environment:
      NAME_NODE_PORT: 9000
      NAME_NODE_ADDR: namenode
      SECOND_NAMENODE_ADDRESS: secnamenode
      NODE_IPS: "datanode1,datanode2,datanode3"
      SERVER_ROLE: "nn"
      FORMAT_NAMENODE: "true"
      START_YARN: "true"
      HIVE_MYSQL_ADDR: hadoopmysql
      YARN_DIR: "/data/yarn"
      DATA_DIR: "/data/hdfs/dn,/data2/hdfs/dn"
      NAME_DIR: "/data/hdfs/nn"
      TMP_DIR: "/data/hdfs/tmp"
      IMPALA_CATALOG_SERVICE_HOST: secnamenode
      IMPALA_STATE_STORE_HOST: secnamenode
      KUDU_MASTER_HOST: "kudu-master:7051,kudu-master2:7051"
    restart: unless-stopped
    ports:
      - "0.0.0.0:8088:8088"
      - "0.0.0.0:50070:50070"
    networks:
      - esnet
    volumes:
      - hadoop_namenode_data:/data
    depends_on:
      - hadoopmysql
  
  secnamenode:
    image: cdh:wzh
    environment:
      NAME_NODE_PORT: 9000
      NAME_NODE_ADDR: namenode
      SECOND_NAMENODE_ADDRESS: secnamenode
      NODE_IPS: "datanode1,datanode2,datanode3"
      SERVER_ROLE: "sn"
      FORMAT_NAMENODE: "true"
      START_YARN: "true"
      HIVE_MYSQL_ADDR: hadoopmysql
      YARN_DIR: "/data/yarn"
      DATA_DIR: "/data/hdfs/dn,/data2/hdfs/dn"
      NAME_DIR: "/data/hdfs/nn"
      TMP_DIR: "/data/hdfs/tmp"
      IMPALA_CATALOG_SERVICE_HOST: secnamenode
      IMPALA_STATE_STORE_HOST: secnamenode
      KUDU_MASTER_HOST: "kudu-master:7051,kudu-master2:7051"
    restart: unless-stopped
    ports:
      - "0.0.0.0:50090:50090"
    networks:
      - esnet
    volumes:
      - hadoop_sec_namenode_data:/data
    depends_on:
      - hadoopmysql

  datanode1:
    image: cdh:wzh
    environment:
      NAME_NODE_PORT: 9000
      NAME_NODE_ADDR: namenode
      SECOND_NAMENODE_ADDRESS: secnamenode
      NODE_IPS: "datanode1,datanode2,datanode3"
      SERVER_ROLE: "dn"
      FORMAT_NAMENODE: "true"
      START_YARN: "true"
      YARN_DIR: "/data/yarn"
      DATA_DIR: "/data/hdfs/dn,/data2/hdfs/dn"
      NAME_DIR: "/data/hdfs/nn"
      TMP_DIR: "/data/hdfs/tmp"
      IMPALA_CATALOG_SERVICE_HOST: secnamenode
      IMPALA_STATE_STORE_HOST: secnamenode
      KUDU_MASTER_HOST: "kudu-master:7051,kudu-master2:7051"
    restart: unless-stopped
    networks:
      - esnet
    volumes:
      - hadoop_datanode1_data:/data
      - hadoop_datanode1_1_data:/data2
    depends_on:
      - namenode

  datanode2:
    image: cdh:wzh
    environment:
      NAME_NODE_PORT: 9000
      NAME_NODE_ADDR: namenode
      SECOND_NAMENODE_ADDRESS: secnamenode
      NODE_IPS: "datanode1,datanode2,datanode3"
      SERVER_ROLE: "dn"
      FORMAT_NAMENODE: "true"
      START_YARN: "true"
      YARN_DIR: "/data/yarn"
      DATA_DIR: "/data/hdfs/dn,/data2/hdfs/dn"
      NAME_DIR: "/data/hdfs/nn"
      TMP_DIR: "/data/hdfs/tmp"
      IMPALA_CATALOG_SERVICE_HOST: secnamenode
      IMPALA_STATE_STORE_HOST: secnamenode
      KUDU_MASTER_HOST: "kudu-master:7051,kudu-master2:7051"
    restart: unless-stopped
    networks:
      - esnet
    volumes:
      - hadoop_datanode2_data:/data
      - hadoop_datanode2_1_data:/data2
    depends_on:
      - namenode

  datanode3:
    image: cdh:wzh
    environment:
      NAME_NODE_PORT: 9000
      NAME_NODE_ADDR: namenode
      SECOND_NAMENODE_ADDRESS: secnamenode
      NODE_IPS: "datanode1,datanode2,datanode3"
      SERVER_ROLE: "dn"
      FORMAT_NAMENODE: "true"
      START_YARN: "true"
      YARN_DIR: "/data/yarn"
      DATA_DIR: "/data/hdfs/dn,/data2/hdfs/dn"
      NAME_DIR: "/data/hdfs/nn"
      TMP_DIR: "/data/hdfs/tmp"
      IMPALA_CATALOG_SERVICE_HOST: secnamenode
      IMPALA_STATE_STORE_HOST: secnamenode
      KUDU_MASTER_HOST: "kudu-master:7051,kudu-master2:7051"
    restart: unless-stopped
    networks:
      - esnet
    volumes:
      - hadoop_datanode3_data:/data
      - hadoop_datanode3_1_data:/data2
    depends_on:
      - namenode


  kudu-master:
    image: kudu:wzh
    environment:
      - KUDU_MASTER=kudu-master,kudu-master2
    command: master
    ports:
      - 0.0.0.0:8051:8051
    volumes:
      - kudu-master:/var/lib/kudu/
    networks:
      - esnet

  kudu-master2:
    image: kudu:wzh
    environment:
      - KUDU_MASTER=kudu-master,kudu-master2
    command: master
    ports:
      - 0.0.0.0:18051:8051
    volumes:
      - kudu-master2:/var/lib/kudu/
    networks:
      - esnet

  kudu-tserver:
    image: kudu:wzh
    environment:
      - KUDU_MASTER=kudu-master,kudu-master2
    command: tserver
    ports:
      - 0.0.0.0:8050:8050
    volumes:
      - kudu-tserver:/var/lib/kudu/
    networks:
      - esnet

  kudu-tserver2:
    image: kudu:wzh
    environment:
      - KUDU_MASTER=kudu-master,kudu-master2
    command: tserver
    ports:
      - 0.0.0.0:18050:8050
    volumes:
      - kudu-tserver2:/var/lib/kudu/
    networks:
      - esnet
  
  kudu-tserver3:
    image: kudu:wzh
    environment:
      - KUDU_MASTER=kudu-master,kudu-master2
    command: tserver
    ports:
      - 0.0.0.0:28050:8050
    volumes:
      - kudu-tserver3:/var/lib/kudu/
    networks:
      - esnet

  nifi:
    image: apache/nifi
    ports:
      - 0.0.0.0:8080:8080
    networks:
      - esnet

volumes:
  kudu-master:
    driver: local
  kudu-master2:
    driver: local
  kudu-tserver:
    driver: local
  kudu-tserver2:
    driver: local
  kudu-tserver3:
    driver: local
  hadoopmysql:
    driver: local
  hadoop_namenode_data:
    driver: local
  hadoop_sec_namenode_data:
    driver: local
  hadoop_datanode1_data:
    driver: local
  hadoop_datanode1_1_data:
    driver: local
  hadoop_datanode2_data:
    driver: local
  hadoop_datanode2_1_data:
    driver: local
  hadoop_datanode3_data:
    driver: local
  hadoop_datanode3_1_data:
    driver: local
  kafka_zoo1_data:
    driver: local
  kafka_zoo1_datalog:
    driver: local
  kafka_kafka1_data:
    driver: local
  esdata1:
    driver: local
  esdata2:
    driver: local
  esdata3:
    driver: local

networks:
  esnet: