version: '3'
services:

  hadoopmysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "hive"
    restart: unless-stopped
    networks:
      - esnet
    volumes:
      - hadoopmysql:/var/lib/mysql

  namenode:
    image: cdh:wzh
    environment:
      NAME_NODE_PORT: 9000
      NAME_NODE_ADDR: namenode
      SECOND_NAMENODE_ADDRESS: secnamenode
      NODE_IPS: "datanode1,datanode2,datanode3"
      SERVER_ROLE: "nn"
      FORMAT_NAMENODE: "true"
      START_YARN: "true"
      HIVE_MYSQL_ADDR: hadoopmysql
    restart: unless-stopped
    ports:
      - "0.0.0.0:8088:8088"
      - "0.0.0.0:50070:50070"
    networks:
      - esnet
    volumes:
      - hadoop_namenode_data:/data
    depends_on:
      - hadoopmysql
  
  secnamenode:
    image: cdh:wzh
    environment:
      NAME_NODE_PORT: 9000
      NAME_NODE_ADDR: namenode
      SECOND_NAMENODE_ADDRESS: secnamenode
      NODE_IPS: "datanode1,datanode2,datanode3"
      SERVER_ROLE: "sn"
      FORMAT_NAMENODE: "true"
      START_YARN: "true"
      HIVE_MYSQL_ADDR: hadoopmysql
    restart: unless-stopped
    ports:
      - "0.0.0.0:50090:50090"
    networks:
      - esnet
    volumes:
      - hadoop_sec_namenode_data:/data
    depends_on:
      - hadoopmysql

  datanode1:
    image: cdh:wzh
    environment:
      NAME_NODE_PORT: 9000
      NAME_NODE_ADDR: namenode
      SECOND_NAMENODE_ADDRESS: secnamenode
      NODE_IPS: "datanode1,datanode2,datanode3"
      SERVER_ROLE: "dn"
      FORMAT_NAMENODE: "true"
      START_YARN: "true"
      DATA_DIR: "/data/hdfs,/data2/hdfs"
    restart: unless-stopped
    networks:
      - esnet
    volumes:
      - hadoop_datanode1_data:/data
      - hadoop_datanode1_1_data:/data2
    depends_on:
      - namenode

  datanode2:
    image: cdh:wzh
    environment:
      NAME_NODE_PORT: 9000
      NAME_NODE_ADDR: namenode
      SECOND_NAMENODE_ADDRESS: secnamenode
      NODE_IPS: "datanode1,datanode2,datanode3"
      SERVER_ROLE: "dn"
      FORMAT_NAMENODE: "true"
      START_YARN: "true"
      DATA_DIR: "/data/hdfs,/data2/hdfs"
    restart: unless-stopped
    networks:
      - esnet
    volumes:
      - hadoop_datanode2_data:/data
      - hadoop_datanode2_1_data:/data2
    depends_on:
      - namenode

  datanode3:
    image: cdh:wzh
    environment:
      NAME_NODE_PORT: 9000
      NAME_NODE_ADDR: namenode
      SECOND_NAMENODE_ADDRESS: secnamenode
      NODE_IPS: "datanode1,datanode2,datanode3"
      SERVER_ROLE: "dn"
      FORMAT_NAMENODE: "true"
      START_YARN: "true"
      DATA_DIR: "/data/hdfs,/data2/hdfs"
    restart: unless-stopped
    networks:
      - esnet
    volumes:
      - hadoop_datanode3_data:/data
      - hadoop_datanode3_1_data:/data2
    depends_on:
      - namenode

volumes:
  hadoopmysql:
    driver: local
  hadoop_namenode_data:
    driver: local
  hadoop_sec_namenode_data:
    driver: local
  hadoop_datanode1_data:
    driver: local
  hadoop_datanode1_1_data:
    driver: local
  hadoop_datanode2_data:
    driver: local
  hadoop_datanode2_1_data:
    driver: local
  hadoop_datanode3_data:
    driver: local
  hadoop_datanode3_1_data:
    driver: local
  kafka_zoo1_data:
    driver: local
  kafka_zoo1_datalog:
    driver: local
  kafka_kafka1_data:
    driver: local
  esdata1:
    driver: local
  esdata2:
    driver: local
  esdata3:
    driver: local

networks:
  esnet: