version: '3'
services:
  syncthing:
    image: syncthing/syncthing
    entrypoint:
      - /bin/syncthing
      - -home
      - /var/syncthing/config
      - -gui-address
      - 10.147.17.28:8384
    volumes:
      - /root/sync:/var/syncthing
    network_mode: "host"
