
filebeat.prospectors:
- type: log
  enabled: true
  paths:
    - /mnt/*.log
    - /mnt/dmesg
    - /mnt/messages
    - /mnt/secure

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

# output.kafka:
#   # initial brokers for reading cluster metadata
#   hosts: ["kafka1:9092"]

#   # message topic selection + partitioning
#   topic: 'wzh_filebeat'
#   partition.round_robin:
#     reachable_only: false

#   required_acks: 1
#   compression: gzip
#   max_message_bytes: 1000000

setup.template.overwrite: true

setup.kibana:
  host: "kibana:5601"

