
filebeat.prospectors:
- type: log
  enabled: true
  paths:
    - /mnt/*.log

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

setup.template.overwrite: true

setup.kibana:
  host: "kibana:5601"