apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: "[\n  {\n    \"apiVersion\": \"couchdb.databases.cloud.ibm.com/v1\"\
      ,\n    \"kind\": \"CouchDBCluster\",\n    \"metadata\": {\n        \"name\"\
      : \"example-couchdbcluster\"\n    },\n    \"spec\": {\n        \"cpu\": \"1\"\
      ,\n        \"disk\": \"1Gi\",\n        \"memory\": \"1Gi\",\n        \"size\"\
      : 3,\n        \"version\": \"2.3.1\",\n        \"environment\": {\n        \
      \    \"adminPassword\": \"changeme\"\n        }\n    }\n  },\n  {\n      \"\
      apiVersion\": \"couchdb.databases.cloud.ibm.com/v1\",\n      \"kind\": \"Formation\"\
      ,\n      \"metadata\": {\n          \"name\": \"example-formation\"\n      },\n\
      \      \"spec\": {}\n  },\n  {\n      \"apiVersion\": \"couchdb.databases.cloud.ibm.com/v1\"\
      ,\n      \"kind\": \"FormationLock\",\n      \"metadata\": {\n          \"name\"\
      : \"example-formationlock\"\n      },\n      \"spec\": {}\n  },\n  {\n     \
      \ \"apiVersion\": \"couchdb.databases.cloud.ibm.com/v1\",\n      \"kind\": \"\
      Recipe\",\n      \"metadata\": {\n          \"name\": \"example-recipe\"\n \
      \     },\n      \"spec\": {}\n  },\n  {\n      \"apiVersion\": \"couchdb.databases.cloud.ibm.com/v1\"\
      ,\n      \"kind\": \"RecipeTemplate\",\n      \"metadata\": {\n          \"\
      name\": \"example-recipetemplate\"\n      },\n      \"spec\": {}\n  },\n  {\n\
      \      \"apiVersion\": \"couchdb.databases.cloud.ibm.com/v1\",\n      \"kind\"\
      : \"ServiceEndpointACL\",\n      \"metadata\": {\n          \"name\": \"example-serviceendpointacl\"\
      \n      },\n      \"spec\": {}\n  },\n  {\n      \"apiVersion\": \"couchdb.databases.cloud.ibm.com/v1\"\
      ,\n      \"kind\": \"Backup\",\n      \"metadata\": {\n          \"name\": \"\
      example-backup\"\n      },\n      \"spec\": {}\n  },\n  {\n      \"apiVersion\"\
      : \"couchdb.databases.cloud.ibm.com/v1\",\n      \"kind\": \"Bucket\",\n   \
      \   \"metadata\": {\n          \"name\": \"example-bucket\"\n      },\n    \
      \  \"spec\": {}\n  }\n]"
    capabilities: Basic Install
    categories: Database
    certified: 'true'
    containerImage: registry.connect.redhat.com/ibm/couchdb-operator
    createdAt: '2019-09-12T12:00:00Z'
    description: Apache CouchDB™ is a highly available database for web and mobile
      applications
    minKubeVersion: 1.11.0
    support: IBM
  name: couchdb-operator.v0.2.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - description: Represents a deployment of an Apache CouchDB™ cluster
        displayName: CouchDB Cluster
        kind: CouchDBCluster
        name: couchdbclusters.couchdb.databases.cloud.ibm.com
        specDescriptors:
          - description: CouchDB Version to be installed
            displayName: CouchDB Version
            path: version
            x-descriptors:
              - urn:alm:descriptor:com.tectonic.ui:label
          - description: Number of CouchDB nodes in the cluster
            displayName: Cluster size
            path: size
            x-descriptors:
              - urn:alm:descriptor:com.tectonic.ui:label
          - description: Storage class to use
            displayName: Storage class
            path: storageClass
            x-descriptors:
              - urn:alm:descriptor:com.tectonic.ui:text
        version: v1
      - description: Internal representation of a CouchDB Cluster. Used internally
          by the Operator for Apache CouchDB.
        displayName: (Internal) CouchDB Formation
        kind: Formation
        name: formations.couchdb.databases.cloud.ibm.com
        version: v1
      - description: Internal representation of a CouchDB Backup. Used internally
          by the Operator for Apache CouchDB.
        displayName: (Internal) CouchDB Backup
        kind: Backup
        name: backups.couchdb.databases.cloud.ibm.com
        version: v1
      - description: Internal representation of a COS Bucket. Used internally by the
          Operator for Apache CouchDB.
        displayName: (Internal) CouchDB Formation
        kind: Bucket
        name: buckets.couchdb.databases.cloud.ibm.com
        version: v1
      - description: Internal lock on a CouchDB Formation. Used internally by the
          Operator for Apache CouchDB.
        displayName: (Internal) CouchDB Formation Lock
        kind: FormationLock
        name: formationlocks.couchdb.databases.cloud.ibm.com
        version: v1
      - description: Internal recipe for CouchDB. Used internally by the Operator
          for Apache CouchDB.
        displayName: (Internal) CouchDB Recipe
        kind: Recipe
        name: recipes.couchdb.databases.cloud.ibm.com
        version: v1
      - description: Internal recipe template for CouchDB. Used internally by the
          Operator for Apache CouchDB.
        displayName: (Internal) CouchDB Recipe Template
        kind: RecipeTemplate
        name: recipetemplates.couchdb.databases.cloud.ibm.com
        version: v1
  description: "The Operator for Apache CouchDB facilitates deploying and managing\
    \ an Apache CouchDB cluster on RedHat OpenShift. \n\n### Operator Features\n*\
    \ Fully automated deployment and configuration of Apache CouchDB clusters.\n*\
    \ Single Operator deployment can support single, multiple, or all namespaces.\n\
    \n### Apache CouchDB Features\nThe Operator for Apache CouchDB uses the following\
    \ defaults when deploying a new Apache CouchDB cluster to ensure a secure and\
    \ highly-available configuration:\n    \n#### Security\n* TLS - The Operator leverages\
    \ the Red Hat OpenShift cert-manager to create certificates and enable HTTPS/SSL\
    \ on the cluster\n* Authentication - The parameter require_valid_user is set to\
    \ true, which means that no requests are allowed from anonymous users. Every request\
    \ must be authenticated.\n* Authorization - Databases are initially accessible\
    \ by Apache CouchDB admins only.\n\n#### High Availability\n* Nodes - Each database\
    \ node in an Apache CouchDB cluster requires its own Kubernetes node. It's recommended\
    \ that you run it with a minimum of three nodes for any production deployment.\n\
    * Zones - The Apache CouchDB cluster database nodes are spread across available\
    \ Kubernetes fault zones where available.\n* Replicas - The default configuration\
    \ for each database is eight shards (Q=8) and three shard copies (N=3), where\
    \ each shard copy is deployed on a separate node in the cluster.\n"
  displayName: Operator for Apache CouchDB
  icon:
    - base64data: PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iaXNvLTg4NTktMSI/Pgo8IS0tIEdlbmVyYXRvcjogQWRvYmUgSWxsdXN0cmF0b3IgMTYuMC4zLCBTVkcgRXhwb3J0IFBsdWctSW4gLiBTVkcgVmVyc2lvbjogNi4wMCBCdWlsZCAwKSAgLS0+CjwhRE9DVFlQRSBzdmcgUFVCTElDICItLy9XM0MvL0RURCBTVkcgMS4xLy9FTiIgImh0dHA6Ly93d3cudzMub3JnL0dyYXBoaWNzL1NWRy8xLjEvRFREL3N2ZzExLmR0ZCI+CjxzdmcgdmVyc2lvbj0iMS4xIiBpZD0iTGF5ZXJfMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgeD0iMHB4IiB5PSIwcHgiCgkgd2lkdGg9IjEwOS43MTRweCIgaGVpZ2h0PSI3MnB4IiB2aWV3Qm94PSIwIDAgMTA5LjcxNCA3MiIgc3R5bGU9ImVuYWJsZS1iYWNrZ3JvdW5kOm5ldyAwIDAgMTA5LjcxNCA3MjsiIHhtbDpzcGFjZT0icHJlc2VydmUiPgo8Zz4KCTxkZWZzPgoJCTxyZWN0IGlkPSJTVkdJRF8xXyIgd2lkdGg9IjEwOS43MTQiIGhlaWdodD0iNzIiLz4KCTwvZGVmcz4KCTxjbGlwUGF0aCBpZD0iU1ZHSURfMl8iPgoJCTx1c2UgeGxpbms6aHJlZj0iI1NWR0lEXzFfIiAgc3R5bGU9Im92ZXJmbG93OnZpc2libGU7Ii8+Cgk8L2NsaXBQYXRoPgoJPHBhdGggc3R5bGU9ImNsaXAtcGF0aDp1cmwoI1NWR0lEXzJfKTtmaWxsOiNFNDI1Mjg7IiBkPSJNODkuMTQzLDQ4YzAsNC41NDctMi4zOTUsNi43NzQtNi44NTcsNi44NTR2MC4wMDNIMjcuNDI5di0wLjAwMwoJCWMtNC40NjItMC4wNzktNi44NTctMi4zMDctNi44NTctNi44NTRjMC00LjU0NiwyLjM5NS02Ljc3NCw2Ljg1Ny02Ljg1NHYtMC4wMDRoNTQuODU2djAuMDA0CgkJQzg2Ljc0OCw0MS4yMjYsODkuMTQzLDQzLjQ1NCw4OS4xNDMsNDggTTgyLjI4NSw1OC4yOXYtMC4wMDRIMjcuNDI5djAuMDA0Yy00LjQ2MiwwLjA3OC02Ljg1NywyLjMwNi02Ljg1Nyw2Ljg1MwoJCXMyLjM5NSw2Ljc3NSw2Ljg1Nyw2Ljg1NFY3Mmg1NC44NTZ2LTAuMDA0YzQuNDYzLTAuMDc4LDYuODU3LTIuMzA3LDYuODU3LTYuODU0Uzg2Ljc0OCw1OC4zNjgsODIuMjg1LDU4LjI5IE05OS40MjksMjAuNTc5di0wLjAwNAoJCWMtNC40NjIsMC4wNzktNi44NTcsMi4zMDctNi44NTcsNi44NTR2MzcuNzE0YzAsNC41NDcsMi4zOTYsNi43NzUsNi44NTcsNi44NTR2LTAuMDA3YzYuNjkzLTAuMjM2LDEwLjI4Ni02LjkyLDEwLjI4Ni0yMC41NjEKCQlWMzQuMjg2QzEwOS43MTUsMjUuMTkzLDEwNi4xMjIsMjAuNzM3LDk5LjQyOSwyMC41NzkgTTEwLjI4NiwyMC41NzV2MC4wMDRDMy41OTQsMjAuNzM3LDAsMjUuMTkzLDAsMzQuMjg2djE3LjE0MwoJCWMwLDEzLjY0MSwzLjU5NCwyMC4zMjQsMTAuMjg2LDIwLjU2MXYwLjAwN2M0LjQ2Mi0wLjA3OCw2Ljg1Ny0yLjMwNyw2Ljg1Ny02Ljg1NFYyNy40MjkKCQlDMTcuMTQzLDIyLjg4MiwxNC43NDgsMjAuNjU0LDEwLjI4NiwyMC41NzUgTTk5LjQyOSwxNy4xNDNjMC0xMS4zNjctNS45ODgtMTYuOTM3LTE3LjE0NC0xNy4xMzNWMEgyNy40Mjl2MC4wMQoJCUMxNi4yNzQsMC4yMDYsMTAuMjg2LDUuNzc2LDEwLjI4NiwxNy4xNDN2MC4wMDZjNi42OTMsMC4xMTgsMTAuMjg2LDMuNDYsMTAuMjg2LDEwLjI4YzAsNi44MiwzLjU5MywxMC4xNjIsMTAuMjg2LDEwLjI4djAuMDA1aDQ4CgkJdi0wLjAwNWM2LjY5Mi0wLjExOCwxMC4yODUtMy40NiwxMC4yODUtMTAuMjhjMC02LjgyLDMuNTkzLTEwLjE2MiwxMC4yODYtMTAuMjhWMTcuMTQzeiIvPgo8L2c+Cjwvc3ZnPgo=
      mediatype: image/svg+xml
  install:
    spec:
      clusterPermissions:
        - rules:
            - apiGroups:
                - ''
              resources:
                - namespaces
                - persistentvolumes
              verbs:
                - get
                - list
                - watch
          serviceAccountName: couchdb-operator
      deployments:
        - name: couchdb-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                name: couchdb-operator
            strategy: {}
            template:
              metadata:
                labels:
                  name: couchdb-operator
              spec:
                containers:
                  - args:
                      - -registry=registry.connect.redhat.com/ibm
                    env:
                      - name: WATCH_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.annotations['olm.targetNamespaces']
                      - name: OPERATOR_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.namespace
                      - name: REGISTRY_SECRET
                        value: ''
                    image: registry.connect.redhat.com/ibm/couchdb-operator:latest
                    imagePullPolicy: Always
                    name: couchdb-operator
                    resources:
                      limits:
                        cpu: 200m
                        memory: 100Mi
                      requests:
                        cpu: 100m
                        memory: 50Mi
                serviceAccountName: couchdb-operator
      permissions:
        - rules:
            - apiGroups:
                - ''
              resources:
                - deployments
                - deployments/scale
                - events
                - endpoints
                - services
                - configmaps
                - secrets
                - pods
                - pods/exec
                - persistentvolumeclaims
                - namespaces
              verbs:
                - '*'
            - apiGroups:
                - ''
              resources:
                - persistentvolumes
              verbs:
                - get
                - update
                - patch
                - list
                - watch
            - apiGroups:
                - apps
              resources:
                - statefulsets
                - replicasets
                - deployments
                - deployments/scale
              verbs:
                - '*'
            - apiGroups:
                - extensions
              resources:
                - networkpolicies
                - deployments
                - deployments/scale
              verbs:
                - '*'
            - apiGroups:
                - networking.k8s.io
              resources:
                - networkpolicies
              verbs:
                - '*'
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - roles
                - rolebindings
              verbs:
                - get
                - create
                - delete
                - update
                - list
                - watch
            - apiGroups:
                - ''
              resources:
                - serviceaccounts
              verbs:
                - get
                - create
                - delete
                - update
                - list
                - watch
            - apiGroups:
                - couchdb.databases.cloud.ibm.com
              resources:
                - '*'
              verbs:
                - '*'
            - apiGroups:
                - batch
              resources:
                - cronjobs
              verbs:
                - '*'
            - apiGroups:
                - policy
              resources:
                - poddisruptionbudgets
              verbs:
                - get
                - create
                - delete
                - list
                - watch
            - apiGroups:
                - apps
              resourceNames:
                - couchdb-operator
              resources:
                - deployments/finalizers
              verbs:
                - update
          serviceAccountName: couchdb-operator
    strategy: deployment
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: true
      type: MultiNamespace
    - supported: true
      type: AllNamespaces
  keywords:
    - Apache
    - CouchDB
    - Cloudant
    - NoSQL
  links:
    - name: Apache CouchDB Homepage
      url: http://couchdb.apache.org/
    - name: Documentation
      url: https://cloud.ibm.com/docs/services/Cloudant?topic=cloudant-apache-couchdb-operator
  maintainers:
    - email: support@cloudant.com
      name: IBM
  maturity: beta
  provider:
    name: IBM
  version: 0.2.0
